// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	waypoints "skyrouter/internal/service/waypoints"

	mock "github.com/stretchr/testify/mock"
)

// MockWaypointRepository is an autogenerated mock type for the WaypointRepository type
type MockWaypointRepository struct {
	mock.Mock
}

type MockWaypointRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWaypointRepository) EXPECT() *MockWaypointRepository_Expecter {
	return &MockWaypointRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockWaypointRepository) GetByID(ctx context.Context, id int32) (*waypoints.Waypoint, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *waypoints.Waypoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*waypoints.Waypoint, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *waypoints.Waypoint); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*waypoints.Waypoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWaypointRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockWaypointRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockWaypointRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockWaypointRepository_GetByID_Call {
	return &MockWaypointRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockWaypointRepository_GetByID_Call) Run(run func(ctx context.Context, id int32)) *MockWaypointRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockWaypointRepository_GetByID_Call) Return(_a0 *waypoints.Waypoint, _a1 error) *MockWaypointRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWaypointRepository_GetByID_Call) RunAndReturn(run func(context.Context, int32) (*waypoints.Waypoint, error)) *MockWaypointRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockWaypointRepository) List(ctx context.Context, filter waypoints.ListWaypointsFilter) ([]waypoints.Waypoint, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []waypoints.Waypoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, waypoints.ListWaypointsFilter) ([]waypoints.Waypoint, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, waypoints.ListWaypointsFilter) []waypoints.Waypoint); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]waypoints.Waypoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, waypoints.ListWaypointsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWaypointRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWaypointRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter waypoints.ListWaypointsFilter
func (_e *MockWaypointRepository_Expecter) List(ctx interface{}, filter interface{}) *MockWaypointRepository_List_Call {
	return &MockWaypointRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockWaypointRepository_List_Call) Run(run func(ctx context.Context, filter waypoints.ListWaypointsFilter)) *MockWaypointRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(waypoints.ListWaypointsFilter))
	})
	return _c
}

func (_c *MockWaypointRepository_List_Call) Return(_a0 []waypoints.Waypoint, _a1 error) *MockWaypointRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWaypointRepository_List_Call) RunAndReturn(run func(context.Context, waypoints.ListWaypointsFilter) ([]waypoints.Waypoint, error)) *MockWaypointRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWaypointRepository creates a new instance of MockWaypointRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWaypointRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWaypointRepository {
	mock := &MockWaypointRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
