// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	flights "skyrouter/internal/service/flights"

	mock "github.com/stretchr/testify/mock"
)

// MockFlightRepository is an autogenerated mock type for the FlightRepository type
type MockFlightRepository struct {
	mock.Mock
}

type MockFlightRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlightRepository) EXPECT() *MockFlightRepository_Expecter {
	return &MockFlightRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockFlightRepository) GetByID(ctx context.Context, id string) (*flights.Flight, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *flights.Flight
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*flights.Flight, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *flights.Flight); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flights.Flight)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlightRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockFlightRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFlightRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockFlightRepository_GetByID_Call {
	return &MockFlightRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockFlightRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockFlightRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFlightRepository_GetByID_Call) Return(_a0 *flights.Flight, _a1 error) *MockFlightRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlightRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*flights.Flight, error)) *MockFlightRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockFlightRepository) List(ctx context.Context, filter flights.ListFlightsFilter) ([]flights.Flight, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []flights.Flight
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, flights.ListFlightsFilter) ([]flights.Flight, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, flights.ListFlightsFilter) []flights.Flight); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]flights.Flight)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, flights.ListFlightsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlightRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFlightRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter flights.ListFlightsFilter
func (_e *MockFlightRepository_Expecter) List(ctx interface{}, filter interface{}) *MockFlightRepository_List_Call {
	return &MockFlightRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockFlightRepository_List_Call) Run(run func(ctx context.Context, filter flights.ListFlightsFilter)) *MockFlightRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(flights.ListFlightsFilter))
	})
	return _c
}

func (_c *MockFlightRepository_List_Call) Return(_a0 []flights.Flight, _a1 error) *MockFlightRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlightRepository_List_Call) RunAndReturn(run func(context.Context, flights.ListFlightsFilter) ([]flights.Flight, error)) *MockFlightRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFlightRepository creates a new instance of MockFlightRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlightRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlightRepository {
	mock := &MockFlightRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
