// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"

	"github.com/aarondl/opt/null"
	models "skyrouter/models"
)

type Factory struct {
	baseGeographyColumnMods GeographyColumnModSlice
	baseGeometryColumnMods  GeometryColumnModSlice
	baseSchemaMigrationMods SchemaMigrationModSlice
	baseSpatialRefSyMods    SpatialRefSyModSlice
	baseWaypointMods        WaypointModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewGeographyColumn(mods ...GeographyColumnMod) *GeographyColumnTemplate {
	return f.NewGeographyColumnWithContext(context.Background(), mods...)
}

func (f *Factory) NewGeographyColumnWithContext(ctx context.Context, mods ...GeographyColumnMod) *GeographyColumnTemplate {
	o := &GeographyColumnTemplate{f: f}

	if f != nil {
		f.baseGeographyColumnMods.Apply(ctx, o)
	}

	GeographyColumnModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingGeographyColumn(m *models.GeographyColumn) *GeographyColumnTemplate {
	o := &GeographyColumnTemplate{f: f, alreadyPersisted: true}

	o.FTableCatalog = func() null.Val[string] { return m.FTableCatalog }
	o.FTableSchema = func() null.Val[string] { return m.FTableSchema }
	o.FTableName = func() null.Val[string] { return m.FTableName }
	o.FGeographyColumn = func() null.Val[string] { return m.FGeographyColumn }
	o.CoordDimension = func() null.Val[int32] { return m.CoordDimension }
	o.Srid = func() null.Val[int32] { return m.Srid }
	o.Type = func() null.Val[string] { return m.Type }

	return o
}

func (f *Factory) NewGeometryColumn(mods ...GeometryColumnMod) *GeometryColumnTemplate {
	return f.NewGeometryColumnWithContext(context.Background(), mods...)
}

func (f *Factory) NewGeometryColumnWithContext(ctx context.Context, mods ...GeometryColumnMod) *GeometryColumnTemplate {
	o := &GeometryColumnTemplate{f: f}

	if f != nil {
		f.baseGeometryColumnMods.Apply(ctx, o)
	}

	GeometryColumnModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingGeometryColumn(m *models.GeometryColumn) *GeometryColumnTemplate {
	o := &GeometryColumnTemplate{f: f, alreadyPersisted: true}

	o.FTableCatalog = func() null.Val[string] { return m.FTableCatalog }
	o.FTableSchema = func() null.Val[string] { return m.FTableSchema }
	o.FTableName = func() null.Val[string] { return m.FTableName }
	o.FGeometryColumn = func() null.Val[string] { return m.FGeometryColumn }
	o.CoordDimension = func() null.Val[int32] { return m.CoordDimension }
	o.Srid = func() null.Val[int32] { return m.Srid }
	o.Type = func() null.Val[string] { return m.Type }

	return o
}

func (f *Factory) NewSchemaMigration(mods ...SchemaMigrationMod) *SchemaMigrationTemplate {
	return f.NewSchemaMigrationWithContext(context.Background(), mods...)
}

func (f *Factory) NewSchemaMigrationWithContext(ctx context.Context, mods ...SchemaMigrationMod) *SchemaMigrationTemplate {
	o := &SchemaMigrationTemplate{f: f}

	if f != nil {
		f.baseSchemaMigrationMods.Apply(ctx, o)
	}

	SchemaMigrationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSchemaMigration(m *models.SchemaMigration) *SchemaMigrationTemplate {
	o := &SchemaMigrationTemplate{f: f, alreadyPersisted: true}

	o.Version = func() int64 { return m.Version }
	o.Dirty = func() bool { return m.Dirty }

	return o
}

func (f *Factory) NewSpatialRefSy(mods ...SpatialRefSyMod) *SpatialRefSyTemplate {
	return f.NewSpatialRefSyWithContext(context.Background(), mods...)
}

func (f *Factory) NewSpatialRefSyWithContext(ctx context.Context, mods ...SpatialRefSyMod) *SpatialRefSyTemplate {
	o := &SpatialRefSyTemplate{f: f}

	if f != nil {
		f.baseSpatialRefSyMods.Apply(ctx, o)
	}

	SpatialRefSyModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSpatialRefSy(m *models.SpatialRefSy) *SpatialRefSyTemplate {
	o := &SpatialRefSyTemplate{f: f, alreadyPersisted: true}

	o.Srid = func() int32 { return m.Srid }
	o.AuthName = func() null.Val[string] { return m.AuthName }
	o.AuthSrid = func() null.Val[int32] { return m.AuthSrid }
	o.Srtext = func() null.Val[string] { return m.Srtext }
	o.Proj4text = func() null.Val[string] { return m.Proj4text }

	return o
}

func (f *Factory) NewWaypoint(mods ...WaypointMod) *WaypointTemplate {
	return f.NewWaypointWithContext(context.Background(), mods...)
}

func (f *Factory) NewWaypointWithContext(ctx context.Context, mods ...WaypointMod) *WaypointTemplate {
	o := &WaypointTemplate{f: f}

	if f != nil {
		f.baseWaypointMods.Apply(ctx, o)
	}

	WaypointModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingWaypoint(m *models.Waypoint) *WaypointTemplate {
	o := &WaypointTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.Name = func() string { return m.Name }
	o.Latitude = func() float64 { return m.Latitude }
	o.Longitude = func() float64 { return m.Longitude }
	o.Location = func() null.Val[string] { return m.Location }

	return o
}

func (f *Factory) ClearBaseGeographyColumnMods() {
	f.baseGeographyColumnMods = nil
}

func (f *Factory) AddBaseGeographyColumnMod(mods ...GeographyColumnMod) {
	f.baseGeographyColumnMods = append(f.baseGeographyColumnMods, mods...)
}

func (f *Factory) ClearBaseGeometryColumnMods() {
	f.baseGeometryColumnMods = nil
}

func (f *Factory) AddBaseGeometryColumnMod(mods ...GeometryColumnMod) {
	f.baseGeometryColumnMods = append(f.baseGeometryColumnMods, mods...)
}

func (f *Factory) ClearBaseSchemaMigrationMods() {
	f.baseSchemaMigrationMods = nil
}

func (f *Factory) AddBaseSchemaMigrationMod(mods ...SchemaMigrationMod) {
	f.baseSchemaMigrationMods = append(f.baseSchemaMigrationMods, mods...)
}

func (f *Factory) ClearBaseSpatialRefSyMods() {
	f.baseSpatialRefSyMods = nil
}

func (f *Factory) AddBaseSpatialRefSyMod(mods ...SpatialRefSyMod) {
	f.baseSpatialRefSyMods = append(f.baseSpatialRefSyMods, mods...)
}

func (f *Factory) ClearBaseWaypointMods() {
	f.baseWaypointMods = nil
}

func (f *Factory) AddBaseWaypointMod(mods ...WaypointMod) {
	f.baseWaypointMods = append(f.baseWaypointMods, mods...)
}
