// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for geography_columns
	geographyColumnWithParentsCascadingCtx = newContextual[bool]("geographyColumnWithParentsCascading")

	// Relationship Contexts for geometry_columns
	geometryColumnWithParentsCascadingCtx = newContextual[bool]("geometryColumnWithParentsCascading")

	// Relationship Contexts for schema_migrations
	schemaMigrationWithParentsCascadingCtx = newContextual[bool]("schemaMigrationWithParentsCascading")

	// Relationship Contexts for spatial_ref_sys
	spatialRefSyWithParentsCascadingCtx = newContextual[bool]("spatialRefSyWithParentsCascading")

	// Relationship Contexts for waypoints
	waypointWithParentsCascadingCtx = newContextual[bool]("waypointWithParentsCascading")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
