// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "skyrouter/models"
)

type WaypointMod interface {
	Apply(context.Context, *WaypointTemplate)
}

type WaypointModFunc func(context.Context, *WaypointTemplate)

func (f WaypointModFunc) Apply(ctx context.Context, n *WaypointTemplate) {
	f(ctx, n)
}

type WaypointModSlice []WaypointMod

func (mods WaypointModSlice) Apply(ctx context.Context, n *WaypointTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// WaypointTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type WaypointTemplate struct {
	ID        func() int32
	Name      func() string
	Latitude  func() float64
	Longitude func() float64
	Location  func() null.Val[string]

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the WaypointTemplate
func (o *WaypointTemplate) Apply(ctx context.Context, mods ...WaypointMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Waypoint
// according to the relationships in the template. Nothing is inserted into the db
func (t WaypointTemplate) setModelRels(o *models.Waypoint) {}

// BuildSetter returns an *models.WaypointSetter
// this does nothing with the relationship templates
func (o WaypointTemplate) BuildSetter() *models.WaypointSetter {
	m := &models.WaypointSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Latitude != nil {
		val := o.Latitude()
		m.Latitude = omit.From(val)
	}
	if o.Longitude != nil {
		val := o.Longitude()
		m.Longitude = omit.From(val)
	}
	if o.Location != nil {
		val := o.Location()
		m.Location = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.WaypointSetter
// this does nothing with the relationship templates
func (o WaypointTemplate) BuildManySetter(number int) []*models.WaypointSetter {
	m := make([]*models.WaypointSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Waypoint
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use WaypointTemplate.Create
func (o WaypointTemplate) Build() *models.Waypoint {
	m := &models.Waypoint{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Latitude != nil {
		m.Latitude = o.Latitude()
	}
	if o.Longitude != nil {
		m.Longitude = o.Longitude()
	}
	if o.Location != nil {
		m.Location = o.Location()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.WaypointSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use WaypointTemplate.CreateMany
func (o WaypointTemplate) BuildMany(number int) models.WaypointSlice {
	m := make(models.WaypointSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableWaypoint(m *models.WaypointSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil, "10")
		m.Name = omit.From(val)
	}
	if !(m.Latitude.IsValue()) {
		val := random_float64(nil)
		m.Latitude = omit.From(val)
	}
	if !(m.Longitude.IsValue()) {
		val := random_float64(nil)
		m.Longitude = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Waypoint
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *WaypointTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Waypoint) error {
	var err error

	return err
}

// Create builds a waypoint and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *WaypointTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Waypoint, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableWaypoint(opt)

	m, err := models.Waypoints.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a waypoint and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *WaypointTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Waypoint {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a waypoint and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *WaypointTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Waypoint {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple waypoints and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o WaypointTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.WaypointSlice, error) {
	var err error
	m := make(models.WaypointSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple waypoints and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o WaypointTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.WaypointSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple waypoints and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o WaypointTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.WaypointSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Waypoint has methods that act as mods for the WaypointTemplate
var WaypointMods waypointMods

type waypointMods struct{}

func (m waypointMods) RandomizeAllColumns(f *faker.Faker) WaypointMod {
	return WaypointModSlice{
		WaypointMods.RandomID(f),
		WaypointMods.RandomName(f),
		WaypointMods.RandomLatitude(f),
		WaypointMods.RandomLongitude(f),
		WaypointMods.RandomLocation(f),
	}
}

// Set the model columns to this value
func (m waypointMods) ID(val int32) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m waypointMods) IDFunc(f func() int32) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m waypointMods) UnsetID() WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m waypointMods) RandomID(f *faker.Faker) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m waypointMods) Name(val string) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m waypointMods) NameFunc(f func() string) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m waypointMods) UnsetName() WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m waypointMods) RandomName(f *faker.Faker) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Name = func() string {
			return random_string(f, "10")
		}
	})
}

// Set the model columns to this value
func (m waypointMods) Latitude(val float64) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Latitude = func() float64 { return val }
	})
}

// Set the Column from the function
func (m waypointMods) LatitudeFunc(f func() float64) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Latitude = f
	})
}

// Clear any values for the column
func (m waypointMods) UnsetLatitude() WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Latitude = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m waypointMods) RandomLatitude(f *faker.Faker) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Latitude = func() float64 {
			return random_float64(f)
		}
	})
}

// Set the model columns to this value
func (m waypointMods) Longitude(val float64) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Longitude = func() float64 { return val }
	})
}

// Set the Column from the function
func (m waypointMods) LongitudeFunc(f func() float64) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Longitude = f
	})
}

// Clear any values for the column
func (m waypointMods) UnsetLongitude() WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Longitude = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m waypointMods) RandomLongitude(f *faker.Faker) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Longitude = func() float64 {
			return random_float64(f)
		}
	})
}

// Set the model columns to this value
func (m waypointMods) Location(val null.Val[string]) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Location = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m waypointMods) LocationFunc(f func() null.Val[string]) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Location = f
	})
}

// Clear any values for the column
func (m waypointMods) UnsetLocation() WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Location = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m waypointMods) RandomLocation(f *faker.Faker) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Location = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m waypointMods) RandomLocationNotNull(f *faker.Faker) WaypointMod {
	return WaypointModFunc(func(_ context.Context, o *WaypointTemplate) {
		o.Location = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

func (m waypointMods) WithParentsCascading() WaypointMod {
	return WaypointModFunc(func(ctx context.Context, o *WaypointTemplate) {
		if isDone, _ := waypointWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = waypointWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
