// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

var GeographyColumns = Table[
	geographyColumnColumns,
	geographyColumnIndexes,
	geographyColumnForeignKeys,
	geographyColumnUniques,
	geographyColumnChecks,
]{
	Schema: "",
	Name:   "geography_columns",
	Columns: geographyColumnColumns{
		FTableCatalog: column{
			Name:      "f_table_catalog",
			DBType:    "name",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		FTableSchema: column{
			Name:      "f_table_schema",
			DBType:    "name",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		FTableName: column{
			Name:      "f_table_name",
			DBType:    "name",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		FGeographyColumn: column{
			Name:      "f_geography_column",
			DBType:    "name",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CoordDimension: column{
			Name:      "coord_dimension",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Srid: column{
			Name:      "srid",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Type: column{
			Name:      "type",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},

	Comment: "",
}

type geographyColumnColumns struct {
	FTableCatalog    column
	FTableSchema     column
	FTableName       column
	FGeographyColumn column
	CoordDimension   column
	Srid             column
	Type             column
}

func (c geographyColumnColumns) AsSlice() []column {
	return []column{
		c.FTableCatalog, c.FTableSchema, c.FTableName, c.FGeographyColumn, c.CoordDimension, c.Srid, c.Type,
	}
}

type geographyColumnIndexes struct{}

func (i geographyColumnIndexes) AsSlice() []index {
	return []index{}
}

type geographyColumnForeignKeys struct{}

func (f geographyColumnForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type geographyColumnUniques struct{}

func (u geographyColumnUniques) AsSlice() []constraint {
	return []constraint{}
}

type geographyColumnChecks struct{}

func (c geographyColumnChecks) AsSlice() []check {
	return []check{}
}
