// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

var GeometryColumns = Table[
	geometryColumnColumns,
	geometryColumnIndexes,
	geometryColumnForeignKeys,
	geometryColumnUniques,
	geometryColumnChecks,
]{
	Schema: "",
	Name:   "geometry_columns",
	Columns: geometryColumnColumns{
		FTableCatalog: column{
			Name:      "f_table_catalog",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		FTableSchema: column{
			Name:      "f_table_schema",
			DBType:    "name",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		FTableName: column{
			Name:      "f_table_name",
			DBType:    "name",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		FGeometryColumn: column{
			Name:      "f_geometry_column",
			DBType:    "name",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CoordDimension: column{
			Name:      "coord_dimension",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Srid: column{
			Name:      "srid",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Type: column{
			Name:      "type",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},

	Comment: "",
}

type geometryColumnColumns struct {
	FTableCatalog   column
	FTableSchema    column
	FTableName      column
	FGeometryColumn column
	CoordDimension  column
	Srid            column
	Type            column
}

func (c geometryColumnColumns) AsSlice() []column {
	return []column{
		c.FTableCatalog, c.FTableSchema, c.FTableName, c.FGeometryColumn, c.CoordDimension, c.Srid, c.Type,
	}
}

type geometryColumnIndexes struct{}

func (i geometryColumnIndexes) AsSlice() []index {
	return []index{}
}

type geometryColumnForeignKeys struct{}

func (f geometryColumnForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type geometryColumnUniques struct{}

func (u geometryColumnUniques) AsSlice() []constraint {
	return []constraint{}
}

type geometryColumnChecks struct{}

func (c geometryColumnChecks) AsSlice() []check {
	return []check{}
}
