// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Waypoints = Table[
	waypointColumns,
	waypointIndexes,
	waypointForeignKeys,
	waypointUniques,
	waypointChecks,
]{
	Schema: "",
	Name:   "waypoints",
	Columns: waypointColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('waypoints_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Latitude: column{
			Name:      "latitude",
			DBType:    "double precision",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Longitude: column{
			Name:      "longitude",
			DBType:    "double precision",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Location: column{
			Name:      "location",
			DBType:    "geography",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: waypointIndexes{
		WaypointsPkey: index{
			Type: "btree",
			Name: "waypoints_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		WaypointsNameKey: index{
			Type: "btree",
			Name: "waypoints_name_key",
			Columns: []indexColumn{
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "waypoints_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: waypointUniques{
		WaypointsNameKey: constraint{
			Name:    "waypoints_name_key",
			Columns: []string{"name"},
			Comment: "",
		},
	},

	Comment: "",
}

type waypointColumns struct {
	ID        column
	Name      column
	Latitude  column
	Longitude column
	Location  column
}

func (c waypointColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Latitude, c.Longitude, c.Location,
	}
}

type waypointIndexes struct {
	WaypointsPkey    index
	WaypointsNameKey index
}

func (i waypointIndexes) AsSlice() []index {
	return []index{
		i.WaypointsPkey, i.WaypointsNameKey,
	}
}

type waypointForeignKeys struct{}

func (f waypointForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type waypointUniques struct {
	WaypointsNameKey constraint
}

func (u waypointUniques) AsSlice() []constraint {
	return []constraint{
		u.WaypointsNameKey,
	}
}

type waypointChecks struct{}

func (c waypointChecks) AsSlice() []check {
	return []check{}
}
