// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SpatialRefSyErrors = &spatialRefSyErrors{
	ErrUniqueSpatialRefSysPkey: &UniqueConstraintError{
		schema:  "",
		table:   "spatial_ref_sys",
		columns: []string{"srid"},
		s:       "spatial_ref_sys_pkey",
	},
}

type spatialRefSyErrors struct {
	ErrUniqueSpatialRefSysPkey *UniqueConstraintError
}
