// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var WaypointErrors = &waypointErrors{
	ErrUniqueWaypointsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "waypoints",
		columns: []string{"id"},
		s:       "waypoints_pkey",
	},

	ErrUniqueWaypointsNameKey: &UniqueConstraintError{
		schema:  "",
		table:   "waypoints",
		columns: []string{"name"},
		s:       "waypoints_name_key",
	},
}

type waypointErrors struct {
	ErrUniqueWaypointsPkey *UniqueConstraintError

	ErrUniqueWaypointsNameKey *UniqueConstraintError
}
