// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type GeographyColumn runs hooks after queries
var _ bob.HookableType = &GeographyColumn{}

// Make sure the type GeometryColumn runs hooks after queries
var _ bob.HookableType = &GeometryColumn{}

// Make sure the type SchemaMigration runs hooks after queries
var _ bob.HookableType = &SchemaMigration{}

// Make sure the type SpatialRefSy runs hooks after queries
var _ bob.HookableType = &SpatialRefSy{}

// Make sure the type Waypoint runs hooks after queries
var _ bob.HookableType = &Waypoint{}
