// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	FlightRouteElements flightRouteElementWhere[Q]
	FlightRouteVersions flightRouteVersionWhere[Q]
	Flights             flightWhere[Q]
	GeographyColumns    geographyColumnWhere[Q]
	GeometryColumns     geometryColumnWhere[Q]
	SchemaMigrations    schemaMigrationWhere[Q]
	SpatialRefSys       spatialRefSyWhere[Q]
	WaypointEdges       waypointEdgeWhere[Q]
	Waypoints           waypointWhere[Q]
} {
	return struct {
		FlightRouteElements flightRouteElementWhere[Q]
		FlightRouteVersions flightRouteVersionWhere[Q]
		Flights             flightWhere[Q]
		GeographyColumns    geographyColumnWhere[Q]
		GeometryColumns     geometryColumnWhere[Q]
		SchemaMigrations    schemaMigrationWhere[Q]
		SpatialRefSys       spatialRefSyWhere[Q]
		WaypointEdges       waypointEdgeWhere[Q]
		Waypoints           waypointWhere[Q]
	}{
		FlightRouteElements: buildFlightRouteElementWhere[Q](FlightRouteElements.Columns),
		FlightRouteVersions: buildFlightRouteVersionWhere[Q](FlightRouteVersions.Columns),
		Flights:             buildFlightWhere[Q](Flights.Columns),
		GeographyColumns:    buildGeographyColumnWhere[Q](GeographyColumns.Columns),
		GeometryColumns:     buildGeometryColumnWhere[Q](GeometryColumns.Columns),
		SchemaMigrations:    buildSchemaMigrationWhere[Q](SchemaMigrations.Columns),
		SpatialRefSys:       buildSpatialRefSyWhere[Q](SpatialRefSys.Columns),
		WaypointEdges:       buildWaypointEdgeWhere[Q](WaypointEdges.Columns),
		Waypoints:           buildWaypointWhere[Q](Waypoints.Columns),
	}
}
