// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/orm"
)

var Preload = getPreloaders()

type preloaders struct {
	FlightRouteElement flightRouteElementPreloader
	FlightRouteVersion flightRouteVersionPreloader
	Flight             flightPreloader
	WaypointEdge       waypointEdgePreloader
	Waypoint           waypointPreloader
}

func getPreloaders() preloaders {
	return preloaders{
		FlightRouteElement: buildFlightRouteElementPreloader(),
		FlightRouteVersion: buildFlightRouteVersionPreloader(),
		Flight:             buildFlightPreloader(),
		WaypointEdge:       buildWaypointEdgePreloader(),
		Waypoint:           buildWaypointPreloader(),
	}
}

var (
	SelectThenLoad = getThenLoaders[*dialect.SelectQuery]()
	InsertThenLoad = getThenLoaders[*dialect.InsertQuery]()
	UpdateThenLoad = getThenLoaders[*dialect.UpdateQuery]()
)

type thenLoaders[Q orm.Loadable] struct {
	FlightRouteElement flightRouteElementThenLoader[Q]
	FlightRouteVersion flightRouteVersionThenLoader[Q]
	Flight             flightThenLoader[Q]
	WaypointEdge       waypointEdgeThenLoader[Q]
	Waypoint           waypointThenLoader[Q]
}

func getThenLoaders[Q orm.Loadable]() thenLoaders[Q] {
	return thenLoaders[Q]{
		FlightRouteElement: buildFlightRouteElementThenLoader[Q](),
		FlightRouteVersion: buildFlightRouteVersionThenLoader[Q](),
		Flight:             buildFlightThenLoader[Q](),
		WaypointEdge:       buildWaypointEdgeThenLoader[Q](),
		Waypoint:           buildWaypointThenLoader[Q](),
	}
}

func thenLoadBuilder[Q orm.Loadable, T any](name string, f func(context.Context, bob.Executor, T, ...bob.Mod[*dialect.SelectQuery]) error) func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q] {
	return func(queryMods ...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q] {
		return func(ctx context.Context, exec bob.Executor, retrieved any) error {
			loader, isLoader := retrieved.(T)
			if !isLoader {
				return fmt.Errorf("object %T cannot load %q", retrieved, name)
			}

			err := f(ctx, exec, loader, queryMods...)

			// Don't cause an issue due to missing relationships
			if errors.Is(err, sql.ErrNoRows) {
				return nil
			}

			return err
		}
	}
}
