// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Flight is an object representing the database table.
type Flight struct {
	ID                    uuid.UUID                             `db:"id,pk" `
	SourceID              string                                `db:"source_id" `
	MessageType           string                                `db:"message_type" `
	Callsign              string                                `db:"callsign" `
	FlightType            null.Val[string]                      `db:"flight_type" `
	Operator              null.Val[string]                      `db:"operator" `
	SRC                   null.Val[string]                      `db:"src" `
	Remark                null.Val[string]                      `db:"remark" `
	AircraftType          null.Val[string]                      `db:"aircraft_type" `
	WakeTurbulence        null.Val[string]                      `db:"wake_turbulence" `
	AircraftRegistration  null.Val[string]                      `db:"aircraft_registration" `
	AircraftAddress       null.Val[string]                      `db:"aircraft_address" `
	AircraftCapabilities  null.Val[types.JSON[json.RawMessage]] `db:"aircraft_capabilities" `
	DepartureAerodrome    string                                `db:"departure_aerodrome" `
	DateOfFlight          time.Time                             `db:"date_of_flight" `
	EstimatedOffBlockTime null.Val[time.Time]                   `db:"estimated_off_block_time" `
	ScheduledDepartureAt  null.Val[time.Time]                   `db:"scheduled_departure_at" `
	DestinationAerodrome  string                                `db:"destination_aerodrome" `
	AlternateAerodromes   null.Val[pq.StringArray]              `db:"alternate_aerodromes" `
	ScheduledArrivalAt    null.Val[time.Time]                   `db:"scheduled_arrival_at" `
	AlternateEnroute      null.Val[string]                      `db:"alternate_enroute" `
	ModeACode             null.Val[string]                      `db:"mode_a_code" `
	Gufi                  null.Val[string]                      `db:"gufi" `
	GufiOriginator        null.Val[string]                      `db:"gufi_originator" `
	ReceptionTime         null.Val[time.Time]                   `db:"reception_time" `
	LastUpdatedAt         null.Val[time.Time]                   `db:"last_updated_at" `
	CreatedAt             time.Time                             `db:"created_at" `

	R flightR `db:"-" `
}

// FlightSlice is an alias for a slice of pointers to Flight.
// This should almost always be used instead of []*Flight.
type FlightSlice []*Flight

// Flights contains methods to work with the flights table
var Flights = psql.NewTablex[*Flight, FlightSlice, *FlightSetter]("", "flights", buildFlightColumns("flights"))

// FlightsQuery is a query on the flights table
type FlightsQuery = *psql.ViewQuery[*Flight, FlightSlice]

// flightR is where relationships are stored.
type flightR struct {
	FlightRouteVersions FlightRouteVersionSlice // flight_route_versions.flight_route_versions_flight_id_fkey
}

func buildFlightColumns(alias string) flightColumns {
	return flightColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "source_id", "message_type", "callsign", "flight_type", "operator", "src", "remark", "aircraft_type", "wake_turbulence", "aircraft_registration", "aircraft_address", "aircraft_capabilities", "departure_aerodrome", "date_of_flight", "estimated_off_block_time", "scheduled_departure_at", "destination_aerodrome", "alternate_aerodromes", "scheduled_arrival_at", "alternate_enroute", "mode_a_code", "gufi", "gufi_originator", "reception_time", "last_updated_at", "created_at",
		).WithParent("flights"),
		tableAlias:            alias,
		ID:                    psql.Quote(alias, "id"),
		SourceID:              psql.Quote(alias, "source_id"),
		MessageType:           psql.Quote(alias, "message_type"),
		Callsign:              psql.Quote(alias, "callsign"),
		FlightType:            psql.Quote(alias, "flight_type"),
		Operator:              psql.Quote(alias, "operator"),
		SRC:                   psql.Quote(alias, "src"),
		Remark:                psql.Quote(alias, "remark"),
		AircraftType:          psql.Quote(alias, "aircraft_type"),
		WakeTurbulence:        psql.Quote(alias, "wake_turbulence"),
		AircraftRegistration:  psql.Quote(alias, "aircraft_registration"),
		AircraftAddress:       psql.Quote(alias, "aircraft_address"),
		AircraftCapabilities:  psql.Quote(alias, "aircraft_capabilities"),
		DepartureAerodrome:    psql.Quote(alias, "departure_aerodrome"),
		DateOfFlight:          psql.Quote(alias, "date_of_flight"),
		EstimatedOffBlockTime: psql.Quote(alias, "estimated_off_block_time"),
		ScheduledDepartureAt:  psql.Quote(alias, "scheduled_departure_at"),
		DestinationAerodrome:  psql.Quote(alias, "destination_aerodrome"),
		AlternateAerodromes:   psql.Quote(alias, "alternate_aerodromes"),
		ScheduledArrivalAt:    psql.Quote(alias, "scheduled_arrival_at"),
		AlternateEnroute:      psql.Quote(alias, "alternate_enroute"),
		ModeACode:             psql.Quote(alias, "mode_a_code"),
		Gufi:                  psql.Quote(alias, "gufi"),
		GufiOriginator:        psql.Quote(alias, "gufi_originator"),
		ReceptionTime:         psql.Quote(alias, "reception_time"),
		LastUpdatedAt:         psql.Quote(alias, "last_updated_at"),
		CreatedAt:             psql.Quote(alias, "created_at"),
	}
}

type flightColumns struct {
	expr.ColumnsExpr
	tableAlias            string
	ID                    psql.Expression
	SourceID              psql.Expression
	MessageType           psql.Expression
	Callsign              psql.Expression
	FlightType            psql.Expression
	Operator              psql.Expression
	SRC                   psql.Expression
	Remark                psql.Expression
	AircraftType          psql.Expression
	WakeTurbulence        psql.Expression
	AircraftRegistration  psql.Expression
	AircraftAddress       psql.Expression
	AircraftCapabilities  psql.Expression
	DepartureAerodrome    psql.Expression
	DateOfFlight          psql.Expression
	EstimatedOffBlockTime psql.Expression
	ScheduledDepartureAt  psql.Expression
	DestinationAerodrome  psql.Expression
	AlternateAerodromes   psql.Expression
	ScheduledArrivalAt    psql.Expression
	AlternateEnroute      psql.Expression
	ModeACode             psql.Expression
	Gufi                  psql.Expression
	GufiOriginator        psql.Expression
	ReceptionTime         psql.Expression
	LastUpdatedAt         psql.Expression
	CreatedAt             psql.Expression
}

func (c flightColumns) Alias() string {
	return c.tableAlias
}

func (flightColumns) AliasedAs(alias string) flightColumns {
	return buildFlightColumns(alias)
}

// FlightSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type FlightSetter struct {
	ID                    omit.Val[uuid.UUID]                       `db:"id,pk" `
	SourceID              omit.Val[string]                          `db:"source_id" `
	MessageType           omit.Val[string]                          `db:"message_type" `
	Callsign              omit.Val[string]                          `db:"callsign" `
	FlightType            omitnull.Val[string]                      `db:"flight_type" `
	Operator              omitnull.Val[string]                      `db:"operator" `
	SRC                   omitnull.Val[string]                      `db:"src" `
	Remark                omitnull.Val[string]                      `db:"remark" `
	AircraftType          omitnull.Val[string]                      `db:"aircraft_type" `
	WakeTurbulence        omitnull.Val[string]                      `db:"wake_turbulence" `
	AircraftRegistration  omitnull.Val[string]                      `db:"aircraft_registration" `
	AircraftAddress       omitnull.Val[string]                      `db:"aircraft_address" `
	AircraftCapabilities  omitnull.Val[types.JSON[json.RawMessage]] `db:"aircraft_capabilities" `
	DepartureAerodrome    omit.Val[string]                          `db:"departure_aerodrome" `
	DateOfFlight          omit.Val[time.Time]                       `db:"date_of_flight" `
	EstimatedOffBlockTime omitnull.Val[time.Time]                   `db:"estimated_off_block_time" `
	ScheduledDepartureAt  omitnull.Val[time.Time]                   `db:"scheduled_departure_at" `
	DestinationAerodrome  omit.Val[string]                          `db:"destination_aerodrome" `
	AlternateAerodromes   omitnull.Val[pq.StringArray]              `db:"alternate_aerodromes" `
	ScheduledArrivalAt    omitnull.Val[time.Time]                   `db:"scheduled_arrival_at" `
	AlternateEnroute      omitnull.Val[string]                      `db:"alternate_enroute" `
	ModeACode             omitnull.Val[string]                      `db:"mode_a_code" `
	Gufi                  omitnull.Val[string]                      `db:"gufi" `
	GufiOriginator        omitnull.Val[string]                      `db:"gufi_originator" `
	ReceptionTime         omitnull.Val[time.Time]                   `db:"reception_time" `
	LastUpdatedAt         omitnull.Val[time.Time]                   `db:"last_updated_at" `
	CreatedAt             omit.Val[time.Time]                       `db:"created_at" `
}

func (s FlightSetter) SetColumns() []string {
	vals := make([]string, 0, 27)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.SourceID.IsValue() {
		vals = append(vals, "source_id")
	}
	if s.MessageType.IsValue() {
		vals = append(vals, "message_type")
	}
	if s.Callsign.IsValue() {
		vals = append(vals, "callsign")
	}
	if !s.FlightType.IsUnset() {
		vals = append(vals, "flight_type")
	}
	if !s.Operator.IsUnset() {
		vals = append(vals, "operator")
	}
	if !s.SRC.IsUnset() {
		vals = append(vals, "src")
	}
	if !s.Remark.IsUnset() {
		vals = append(vals, "remark")
	}
	if !s.AircraftType.IsUnset() {
		vals = append(vals, "aircraft_type")
	}
	if !s.WakeTurbulence.IsUnset() {
		vals = append(vals, "wake_turbulence")
	}
	if !s.AircraftRegistration.IsUnset() {
		vals = append(vals, "aircraft_registration")
	}
	if !s.AircraftAddress.IsUnset() {
		vals = append(vals, "aircraft_address")
	}
	if !s.AircraftCapabilities.IsUnset() {
		vals = append(vals, "aircraft_capabilities")
	}
	if s.DepartureAerodrome.IsValue() {
		vals = append(vals, "departure_aerodrome")
	}
	if s.DateOfFlight.IsValue() {
		vals = append(vals, "date_of_flight")
	}
	if !s.EstimatedOffBlockTime.IsUnset() {
		vals = append(vals, "estimated_off_block_time")
	}
	if !s.ScheduledDepartureAt.IsUnset() {
		vals = append(vals, "scheduled_departure_at")
	}
	if s.DestinationAerodrome.IsValue() {
		vals = append(vals, "destination_aerodrome")
	}
	if !s.AlternateAerodromes.IsUnset() {
		vals = append(vals, "alternate_aerodromes")
	}
	if !s.ScheduledArrivalAt.IsUnset() {
		vals = append(vals, "scheduled_arrival_at")
	}
	if !s.AlternateEnroute.IsUnset() {
		vals = append(vals, "alternate_enroute")
	}
	if !s.ModeACode.IsUnset() {
		vals = append(vals, "mode_a_code")
	}
	if !s.Gufi.IsUnset() {
		vals = append(vals, "gufi")
	}
	if !s.GufiOriginator.IsUnset() {
		vals = append(vals, "gufi_originator")
	}
	if !s.ReceptionTime.IsUnset() {
		vals = append(vals, "reception_time")
	}
	if !s.LastUpdatedAt.IsUnset() {
		vals = append(vals, "last_updated_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s FlightSetter) Overwrite(t *Flight) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.SourceID.IsValue() {
		t.SourceID = s.SourceID.MustGet()
	}
	if s.MessageType.IsValue() {
		t.MessageType = s.MessageType.MustGet()
	}
	if s.Callsign.IsValue() {
		t.Callsign = s.Callsign.MustGet()
	}
	if !s.FlightType.IsUnset() {
		t.FlightType = s.FlightType.MustGetNull()
	}
	if !s.Operator.IsUnset() {
		t.Operator = s.Operator.MustGetNull()
	}
	if !s.SRC.IsUnset() {
		t.SRC = s.SRC.MustGetNull()
	}
	if !s.Remark.IsUnset() {
		t.Remark = s.Remark.MustGetNull()
	}
	if !s.AircraftType.IsUnset() {
		t.AircraftType = s.AircraftType.MustGetNull()
	}
	if !s.WakeTurbulence.IsUnset() {
		t.WakeTurbulence = s.WakeTurbulence.MustGetNull()
	}
	if !s.AircraftRegistration.IsUnset() {
		t.AircraftRegistration = s.AircraftRegistration.MustGetNull()
	}
	if !s.AircraftAddress.IsUnset() {
		t.AircraftAddress = s.AircraftAddress.MustGetNull()
	}
	if !s.AircraftCapabilities.IsUnset() {
		t.AircraftCapabilities = s.AircraftCapabilities.MustGetNull()
	}
	if s.DepartureAerodrome.IsValue() {
		t.DepartureAerodrome = s.DepartureAerodrome.MustGet()
	}
	if s.DateOfFlight.IsValue() {
		t.DateOfFlight = s.DateOfFlight.MustGet()
	}
	if !s.EstimatedOffBlockTime.IsUnset() {
		t.EstimatedOffBlockTime = s.EstimatedOffBlockTime.MustGetNull()
	}
	if !s.ScheduledDepartureAt.IsUnset() {
		t.ScheduledDepartureAt = s.ScheduledDepartureAt.MustGetNull()
	}
	if s.DestinationAerodrome.IsValue() {
		t.DestinationAerodrome = s.DestinationAerodrome.MustGet()
	}
	if !s.AlternateAerodromes.IsUnset() {
		t.AlternateAerodromes = s.AlternateAerodromes.MustGetNull()
	}
	if !s.ScheduledArrivalAt.IsUnset() {
		t.ScheduledArrivalAt = s.ScheduledArrivalAt.MustGetNull()
	}
	if !s.AlternateEnroute.IsUnset() {
		t.AlternateEnroute = s.AlternateEnroute.MustGetNull()
	}
	if !s.ModeACode.IsUnset() {
		t.ModeACode = s.ModeACode.MustGetNull()
	}
	if !s.Gufi.IsUnset() {
		t.Gufi = s.Gufi.MustGetNull()
	}
	if !s.GufiOriginator.IsUnset() {
		t.GufiOriginator = s.GufiOriginator.MustGetNull()
	}
	if !s.ReceptionTime.IsUnset() {
		t.ReceptionTime = s.ReceptionTime.MustGetNull()
	}
	if !s.LastUpdatedAt.IsUnset() {
		t.LastUpdatedAt = s.LastUpdatedAt.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *FlightSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Flights.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 27)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.SourceID.IsValue() {
			vals[1] = psql.Arg(s.SourceID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.MessageType.IsValue() {
			vals[2] = psql.Arg(s.MessageType.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Callsign.IsValue() {
			vals[3] = psql.Arg(s.Callsign.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.FlightType.IsUnset() {
			vals[4] = psql.Arg(s.FlightType.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.Operator.IsUnset() {
			vals[5] = psql.Arg(s.Operator.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.SRC.IsUnset() {
			vals[6] = psql.Arg(s.SRC.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.Remark.IsUnset() {
			vals[7] = psql.Arg(s.Remark.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.AircraftType.IsUnset() {
			vals[8] = psql.Arg(s.AircraftType.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.WakeTurbulence.IsUnset() {
			vals[9] = psql.Arg(s.WakeTurbulence.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if !s.AircraftRegistration.IsUnset() {
			vals[10] = psql.Arg(s.AircraftRegistration.MustGetNull())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if !s.AircraftAddress.IsUnset() {
			vals[11] = psql.Arg(s.AircraftAddress.MustGetNull())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if !s.AircraftCapabilities.IsUnset() {
			vals[12] = psql.Arg(s.AircraftCapabilities.MustGetNull())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if s.DepartureAerodrome.IsValue() {
			vals[13] = psql.Arg(s.DepartureAerodrome.MustGet())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		if s.DateOfFlight.IsValue() {
			vals[14] = psql.Arg(s.DateOfFlight.MustGet())
		} else {
			vals[14] = psql.Raw("DEFAULT")
		}

		if !s.EstimatedOffBlockTime.IsUnset() {
			vals[15] = psql.Arg(s.EstimatedOffBlockTime.MustGetNull())
		} else {
			vals[15] = psql.Raw("DEFAULT")
		}

		if !s.ScheduledDepartureAt.IsUnset() {
			vals[16] = psql.Arg(s.ScheduledDepartureAt.MustGetNull())
		} else {
			vals[16] = psql.Raw("DEFAULT")
		}

		if s.DestinationAerodrome.IsValue() {
			vals[17] = psql.Arg(s.DestinationAerodrome.MustGet())
		} else {
			vals[17] = psql.Raw("DEFAULT")
		}

		if !s.AlternateAerodromes.IsUnset() {
			vals[18] = psql.Arg(s.AlternateAerodromes.MustGetNull())
		} else {
			vals[18] = psql.Raw("DEFAULT")
		}

		if !s.ScheduledArrivalAt.IsUnset() {
			vals[19] = psql.Arg(s.ScheduledArrivalAt.MustGetNull())
		} else {
			vals[19] = psql.Raw("DEFAULT")
		}

		if !s.AlternateEnroute.IsUnset() {
			vals[20] = psql.Arg(s.AlternateEnroute.MustGetNull())
		} else {
			vals[20] = psql.Raw("DEFAULT")
		}

		if !s.ModeACode.IsUnset() {
			vals[21] = psql.Arg(s.ModeACode.MustGetNull())
		} else {
			vals[21] = psql.Raw("DEFAULT")
		}

		if !s.Gufi.IsUnset() {
			vals[22] = psql.Arg(s.Gufi.MustGetNull())
		} else {
			vals[22] = psql.Raw("DEFAULT")
		}

		if !s.GufiOriginator.IsUnset() {
			vals[23] = psql.Arg(s.GufiOriginator.MustGetNull())
		} else {
			vals[23] = psql.Raw("DEFAULT")
		}

		if !s.ReceptionTime.IsUnset() {
			vals[24] = psql.Arg(s.ReceptionTime.MustGetNull())
		} else {
			vals[24] = psql.Raw("DEFAULT")
		}

		if !s.LastUpdatedAt.IsUnset() {
			vals[25] = psql.Arg(s.LastUpdatedAt.MustGetNull())
		} else {
			vals[25] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[26] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[26] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s FlightSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s FlightSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 27)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.SourceID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "source_id")...),
			psql.Arg(s.SourceID),
		}})
	}

	if s.MessageType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "message_type")...),
			psql.Arg(s.MessageType),
		}})
	}

	if s.Callsign.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "callsign")...),
			psql.Arg(s.Callsign),
		}})
	}

	if !s.FlightType.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "flight_type")...),
			psql.Arg(s.FlightType),
		}})
	}

	if !s.Operator.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "operator")...),
			psql.Arg(s.Operator),
		}})
	}

	if !s.SRC.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "src")...),
			psql.Arg(s.SRC),
		}})
	}

	if !s.Remark.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "remark")...),
			psql.Arg(s.Remark),
		}})
	}

	if !s.AircraftType.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "aircraft_type")...),
			psql.Arg(s.AircraftType),
		}})
	}

	if !s.WakeTurbulence.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "wake_turbulence")...),
			psql.Arg(s.WakeTurbulence),
		}})
	}

	if !s.AircraftRegistration.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "aircraft_registration")...),
			psql.Arg(s.AircraftRegistration),
		}})
	}

	if !s.AircraftAddress.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "aircraft_address")...),
			psql.Arg(s.AircraftAddress),
		}})
	}

	if !s.AircraftCapabilities.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "aircraft_capabilities")...),
			psql.Arg(s.AircraftCapabilities),
		}})
	}

	if s.DepartureAerodrome.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "departure_aerodrome")...),
			psql.Arg(s.DepartureAerodrome),
		}})
	}

	if s.DateOfFlight.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "date_of_flight")...),
			psql.Arg(s.DateOfFlight),
		}})
	}

	if !s.EstimatedOffBlockTime.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "estimated_off_block_time")...),
			psql.Arg(s.EstimatedOffBlockTime),
		}})
	}

	if !s.ScheduledDepartureAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "scheduled_departure_at")...),
			psql.Arg(s.ScheduledDepartureAt),
		}})
	}

	if s.DestinationAerodrome.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "destination_aerodrome")...),
			psql.Arg(s.DestinationAerodrome),
		}})
	}

	if !s.AlternateAerodromes.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "alternate_aerodromes")...),
			psql.Arg(s.AlternateAerodromes),
		}})
	}

	if !s.ScheduledArrivalAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "scheduled_arrival_at")...),
			psql.Arg(s.ScheduledArrivalAt),
		}})
	}

	if !s.AlternateEnroute.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "alternate_enroute")...),
			psql.Arg(s.AlternateEnroute),
		}})
	}

	if !s.ModeACode.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "mode_a_code")...),
			psql.Arg(s.ModeACode),
		}})
	}

	if !s.Gufi.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "gufi")...),
			psql.Arg(s.Gufi),
		}})
	}

	if !s.GufiOriginator.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "gufi_originator")...),
			psql.Arg(s.GufiOriginator),
		}})
	}

	if !s.ReceptionTime.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "reception_time")...),
			psql.Arg(s.ReceptionTime),
		}})
	}

	if !s.LastUpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_updated_at")...),
			psql.Arg(s.LastUpdatedAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindFlight retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindFlight(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Flight, error) {
	if len(cols) == 0 {
		return Flights.Query(
			sm.Where(Flights.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Flights.Query(
		sm.Where(Flights.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Flights.Columns.Only(cols...)),
	).One(ctx, exec)
}

// FlightExists checks the presence of a single record by primary key
func FlightExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Flights.Query(
		sm.Where(Flights.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Flight is retrieved from the database
func (o *Flight) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Flights.AfterSelectHooks.RunHooks(ctx, exec, FlightSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Flights.AfterInsertHooks.RunHooks(ctx, exec, FlightSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Flights.AfterUpdateHooks.RunHooks(ctx, exec, FlightSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Flights.AfterDeleteHooks.RunHooks(ctx, exec, FlightSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Flight
func (o *Flight) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Flight) pkEQ() dialect.Expression {
	return psql.Quote("flights", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Flight
func (o *Flight) Update(ctx context.Context, exec bob.Executor, s *FlightSetter) error {
	v, err := Flights.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Flight record with an executor
func (o *Flight) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Flights.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Flight using the executor
func (o *Flight) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Flights.Query(
		sm.Where(Flights.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after FlightSlice is retrieved from the database
func (o FlightSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Flights.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Flights.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Flights.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Flights.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o FlightSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("flights", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o FlightSlice) copyMatchingRows(from ...*Flight) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o FlightSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Flights.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Flight:
				o.copyMatchingRows(retrieved)
			case []*Flight:
				o.copyMatchingRows(retrieved...)
			case FlightSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Flight or a slice of Flight
				// then run the AfterUpdateHooks on the slice
				_, err = Flights.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o FlightSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Flights.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Flight:
				o.copyMatchingRows(retrieved)
			case []*Flight:
				o.copyMatchingRows(retrieved...)
			case FlightSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Flight or a slice of Flight
				// then run the AfterDeleteHooks on the slice
				_, err = Flights.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o FlightSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals FlightSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Flights.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o FlightSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Flights.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o FlightSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Flights.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// FlightRouteVersions starts a query for related objects on flight_route_versions
func (o *Flight) FlightRouteVersions(mods ...bob.Mod[*dialect.SelectQuery]) FlightRouteVersionsQuery {
	return FlightRouteVersions.Query(append(mods,
		sm.Where(FlightRouteVersions.Columns.FlightID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os FlightSlice) FlightRouteVersions(mods ...bob.Mod[*dialect.SelectQuery]) FlightRouteVersionsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return FlightRouteVersions.Query(append(mods,
		sm.Where(psql.Group(FlightRouteVersions.Columns.FlightID).OP("IN", PKArgExpr)),
	)...)
}

func insertFlightFlightRouteVersions0(ctx context.Context, exec bob.Executor, flightRouteVersions1 []*FlightRouteVersionSetter, flight0 *Flight) (FlightRouteVersionSlice, error) {
	for i := range flightRouteVersions1 {
		flightRouteVersions1[i].FlightID = omit.From(flight0.ID)
	}

	ret, err := FlightRouteVersions.Insert(bob.ToMods(flightRouteVersions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertFlightFlightRouteVersions0: %w", err)
	}

	return ret, nil
}

func attachFlightFlightRouteVersions0(ctx context.Context, exec bob.Executor, count int, flightRouteVersions1 FlightRouteVersionSlice, flight0 *Flight) (FlightRouteVersionSlice, error) {
	setter := &FlightRouteVersionSetter{
		FlightID: omit.From(flight0.ID),
	}

	err := flightRouteVersions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachFlightFlightRouteVersions0: %w", err)
	}

	return flightRouteVersions1, nil
}

func (flight0 *Flight) InsertFlightRouteVersions(ctx context.Context, exec bob.Executor, related ...*FlightRouteVersionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	flightRouteVersions1, err := insertFlightFlightRouteVersions0(ctx, exec, related, flight0)
	if err != nil {
		return err
	}

	flight0.R.FlightRouteVersions = append(flight0.R.FlightRouteVersions, flightRouteVersions1...)

	for _, rel := range flightRouteVersions1 {
		rel.R.Flight = flight0
	}
	return nil
}

func (flight0 *Flight) AttachFlightRouteVersions(ctx context.Context, exec bob.Executor, related ...*FlightRouteVersion) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	flightRouteVersions1 := FlightRouteVersionSlice(related)

	_, err = attachFlightFlightRouteVersions0(ctx, exec, len(related), flightRouteVersions1, flight0)
	if err != nil {
		return err
	}

	flight0.R.FlightRouteVersions = append(flight0.R.FlightRouteVersions, flightRouteVersions1...)

	for _, rel := range related {
		rel.R.Flight = flight0
	}

	return nil
}

type flightWhere[Q psql.Filterable] struct {
	ID                    psql.WhereMod[Q, uuid.UUID]
	SourceID              psql.WhereMod[Q, string]
	MessageType           psql.WhereMod[Q, string]
	Callsign              psql.WhereMod[Q, string]
	FlightType            psql.WhereNullMod[Q, string]
	Operator              psql.WhereNullMod[Q, string]
	SRC                   psql.WhereNullMod[Q, string]
	Remark                psql.WhereNullMod[Q, string]
	AircraftType          psql.WhereNullMod[Q, string]
	WakeTurbulence        psql.WhereNullMod[Q, string]
	AircraftRegistration  psql.WhereNullMod[Q, string]
	AircraftAddress       psql.WhereNullMod[Q, string]
	AircraftCapabilities  psql.WhereNullMod[Q, types.JSON[json.RawMessage]]
	DepartureAerodrome    psql.WhereMod[Q, string]
	DateOfFlight          psql.WhereMod[Q, time.Time]
	EstimatedOffBlockTime psql.WhereNullMod[Q, time.Time]
	ScheduledDepartureAt  psql.WhereNullMod[Q, time.Time]
	DestinationAerodrome  psql.WhereMod[Q, string]
	AlternateAerodromes   psql.WhereNullMod[Q, pq.StringArray]
	ScheduledArrivalAt    psql.WhereNullMod[Q, time.Time]
	AlternateEnroute      psql.WhereNullMod[Q, string]
	ModeACode             psql.WhereNullMod[Q, string]
	Gufi                  psql.WhereNullMod[Q, string]
	GufiOriginator        psql.WhereNullMod[Q, string]
	ReceptionTime         psql.WhereNullMod[Q, time.Time]
	LastUpdatedAt         psql.WhereNullMod[Q, time.Time]
	CreatedAt             psql.WhereMod[Q, time.Time]
}

func (flightWhere[Q]) AliasedAs(alias string) flightWhere[Q] {
	return buildFlightWhere[Q](buildFlightColumns(alias))
}

func buildFlightWhere[Q psql.Filterable](cols flightColumns) flightWhere[Q] {
	return flightWhere[Q]{
		ID:                    psql.Where[Q, uuid.UUID](cols.ID),
		SourceID:              psql.Where[Q, string](cols.SourceID),
		MessageType:           psql.Where[Q, string](cols.MessageType),
		Callsign:              psql.Where[Q, string](cols.Callsign),
		FlightType:            psql.WhereNull[Q, string](cols.FlightType),
		Operator:              psql.WhereNull[Q, string](cols.Operator),
		SRC:                   psql.WhereNull[Q, string](cols.SRC),
		Remark:                psql.WhereNull[Q, string](cols.Remark),
		AircraftType:          psql.WhereNull[Q, string](cols.AircraftType),
		WakeTurbulence:        psql.WhereNull[Q, string](cols.WakeTurbulence),
		AircraftRegistration:  psql.WhereNull[Q, string](cols.AircraftRegistration),
		AircraftAddress:       psql.WhereNull[Q, string](cols.AircraftAddress),
		AircraftCapabilities:  psql.WhereNull[Q, types.JSON[json.RawMessage]](cols.AircraftCapabilities),
		DepartureAerodrome:    psql.Where[Q, string](cols.DepartureAerodrome),
		DateOfFlight:          psql.Where[Q, time.Time](cols.DateOfFlight),
		EstimatedOffBlockTime: psql.WhereNull[Q, time.Time](cols.EstimatedOffBlockTime),
		ScheduledDepartureAt:  psql.WhereNull[Q, time.Time](cols.ScheduledDepartureAt),
		DestinationAerodrome:  psql.Where[Q, string](cols.DestinationAerodrome),
		AlternateAerodromes:   psql.WhereNull[Q, pq.StringArray](cols.AlternateAerodromes),
		ScheduledArrivalAt:    psql.WhereNull[Q, time.Time](cols.ScheduledArrivalAt),
		AlternateEnroute:      psql.WhereNull[Q, string](cols.AlternateEnroute),
		ModeACode:             psql.WhereNull[Q, string](cols.ModeACode),
		Gufi:                  psql.WhereNull[Q, string](cols.Gufi),
		GufiOriginator:        psql.WhereNull[Q, string](cols.GufiOriginator),
		ReceptionTime:         psql.WhereNull[Q, time.Time](cols.ReceptionTime),
		LastUpdatedAt:         psql.WhereNull[Q, time.Time](cols.LastUpdatedAt),
		CreatedAt:             psql.Where[Q, time.Time](cols.CreatedAt),
	}
}

func (o *Flight) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "FlightRouteVersions":
		rels, ok := retrieved.(FlightRouteVersionSlice)
		if !ok {
			return fmt.Errorf("flight cannot load %T as %q", retrieved, name)
		}

		o.R.FlightRouteVersions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Flight = o
			}
		}
		return nil
	default:
		return fmt.Errorf("flight has no relationship %q", name)
	}
}

type flightPreloader struct{}

func buildFlightPreloader() flightPreloader {
	return flightPreloader{}
}

type flightThenLoader[Q orm.Loadable] struct {
	FlightRouteVersions func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildFlightThenLoader[Q orm.Loadable]() flightThenLoader[Q] {
	type FlightRouteVersionsLoadInterface interface {
		LoadFlightRouteVersions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return flightThenLoader[Q]{
		FlightRouteVersions: thenLoadBuilder[Q](
			"FlightRouteVersions",
			func(ctx context.Context, exec bob.Executor, retrieved FlightRouteVersionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadFlightRouteVersions(ctx, exec, mods...)
			},
		),
	}
}

// LoadFlightRouteVersions loads the flight's FlightRouteVersions into the .R struct
func (o *Flight) LoadFlightRouteVersions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.FlightRouteVersions = nil

	related, err := o.FlightRouteVersions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Flight = o
	}

	o.R.FlightRouteVersions = related
	return nil
}

// LoadFlightRouteVersions loads the flight's FlightRouteVersions into the .R struct
func (os FlightSlice) LoadFlightRouteVersions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	flightRouteVersions, err := os.FlightRouteVersions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.FlightRouteVersions = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range flightRouteVersions {

			if !(o.ID == rel.FlightID) {
				continue
			}

			rel.R.Flight = o

			o.R.FlightRouteVersions = append(o.R.FlightRouteVersions, rel)
		}
	}

	return nil
}

type flightJoins[Q dialect.Joinable] struct {
	typ                 string
	FlightRouteVersions modAs[Q, flightRouteVersionColumns]
}

func (j flightJoins[Q]) aliasedAs(alias string) flightJoins[Q] {
	return buildFlightJoins[Q](buildFlightColumns(alias), j.typ)
}

func buildFlightJoins[Q dialect.Joinable](cols flightColumns, typ string) flightJoins[Q] {
	return flightJoins[Q]{
		typ: typ,
		FlightRouteVersions: modAs[Q, flightRouteVersionColumns]{
			c: FlightRouteVersions.Columns,
			f: func(to flightRouteVersionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, FlightRouteVersions.Name().As(to.Alias())).On(
						to.FlightID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
