// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// FlightRouteVersion is an object representing the database table.
type FlightRouteVersion struct {
	ID               uuid.UUID                `db:"id,pk" `
	FlightID         uuid.UUID                `db:"flight_id" `
	Version          int32                    `db:"version" `
	FlightRules      null.Val[string]         `db:"flight_rules" `
	CruisingSpeed    null.Val[string]         `db:"cruising_speed" `
	CruisingLevel    null.Val[string]         `db:"cruising_level" `
	RouteText        null.Val[string]         `db:"route_text" `
	TotalElapsedTime null.Val[string]         `db:"total_elapsed_time" `
	FirEstimates     null.Val[pq.StringArray] `db:"fir_estimates" `
	CreatedAt        time.Time                `db:"created_at" `

	R flightRouteVersionR `db:"-" `
}

// FlightRouteVersionSlice is an alias for a slice of pointers to FlightRouteVersion.
// This should almost always be used instead of []*FlightRouteVersion.
type FlightRouteVersionSlice []*FlightRouteVersion

// FlightRouteVersions contains methods to work with the flight_route_versions table
var FlightRouteVersions = psql.NewTablex[*FlightRouteVersion, FlightRouteVersionSlice, *FlightRouteVersionSetter]("", "flight_route_versions", buildFlightRouteVersionColumns("flight_route_versions"))

// FlightRouteVersionsQuery is a query on the flight_route_versions table
type FlightRouteVersionsQuery = *psql.ViewQuery[*FlightRouteVersion, FlightRouteVersionSlice]

// flightRouteVersionR is where relationships are stored.
type flightRouteVersionR struct {
	RouteVersionFlightRouteElements FlightRouteElementSlice // flight_route_elements.flight_route_elements_route_version_id_fkey
	Flight                          *Flight                 // flight_route_versions.flight_route_versions_flight_id_fkey
}

func buildFlightRouteVersionColumns(alias string) flightRouteVersionColumns {
	return flightRouteVersionColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "flight_id", "version", "flight_rules", "cruising_speed", "cruising_level", "route_text", "total_elapsed_time", "fir_estimates", "created_at",
		).WithParent("flight_route_versions"),
		tableAlias:       alias,
		ID:               psql.Quote(alias, "id"),
		FlightID:         psql.Quote(alias, "flight_id"),
		Version:          psql.Quote(alias, "version"),
		FlightRules:      psql.Quote(alias, "flight_rules"),
		CruisingSpeed:    psql.Quote(alias, "cruising_speed"),
		CruisingLevel:    psql.Quote(alias, "cruising_level"),
		RouteText:        psql.Quote(alias, "route_text"),
		TotalElapsedTime: psql.Quote(alias, "total_elapsed_time"),
		FirEstimates:     psql.Quote(alias, "fir_estimates"),
		CreatedAt:        psql.Quote(alias, "created_at"),
	}
}

type flightRouteVersionColumns struct {
	expr.ColumnsExpr
	tableAlias       string
	ID               psql.Expression
	FlightID         psql.Expression
	Version          psql.Expression
	FlightRules      psql.Expression
	CruisingSpeed    psql.Expression
	CruisingLevel    psql.Expression
	RouteText        psql.Expression
	TotalElapsedTime psql.Expression
	FirEstimates     psql.Expression
	CreatedAt        psql.Expression
}

func (c flightRouteVersionColumns) Alias() string {
	return c.tableAlias
}

func (flightRouteVersionColumns) AliasedAs(alias string) flightRouteVersionColumns {
	return buildFlightRouteVersionColumns(alias)
}

// FlightRouteVersionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type FlightRouteVersionSetter struct {
	ID               omit.Val[uuid.UUID]          `db:"id,pk" `
	FlightID         omit.Val[uuid.UUID]          `db:"flight_id" `
	Version          omit.Val[int32]              `db:"version" `
	FlightRules      omitnull.Val[string]         `db:"flight_rules" `
	CruisingSpeed    omitnull.Val[string]         `db:"cruising_speed" `
	CruisingLevel    omitnull.Val[string]         `db:"cruising_level" `
	RouteText        omitnull.Val[string]         `db:"route_text" `
	TotalElapsedTime omitnull.Val[string]         `db:"total_elapsed_time" `
	FirEstimates     omitnull.Val[pq.StringArray] `db:"fir_estimates" `
	CreatedAt        omit.Val[time.Time]          `db:"created_at" `
}

func (s FlightRouteVersionSetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.FlightID.IsValue() {
		vals = append(vals, "flight_id")
	}
	if s.Version.IsValue() {
		vals = append(vals, "version")
	}
	if !s.FlightRules.IsUnset() {
		vals = append(vals, "flight_rules")
	}
	if !s.CruisingSpeed.IsUnset() {
		vals = append(vals, "cruising_speed")
	}
	if !s.CruisingLevel.IsUnset() {
		vals = append(vals, "cruising_level")
	}
	if !s.RouteText.IsUnset() {
		vals = append(vals, "route_text")
	}
	if !s.TotalElapsedTime.IsUnset() {
		vals = append(vals, "total_elapsed_time")
	}
	if !s.FirEstimates.IsUnset() {
		vals = append(vals, "fir_estimates")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s FlightRouteVersionSetter) Overwrite(t *FlightRouteVersion) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.FlightID.IsValue() {
		t.FlightID = s.FlightID.MustGet()
	}
	if s.Version.IsValue() {
		t.Version = s.Version.MustGet()
	}
	if !s.FlightRules.IsUnset() {
		t.FlightRules = s.FlightRules.MustGetNull()
	}
	if !s.CruisingSpeed.IsUnset() {
		t.CruisingSpeed = s.CruisingSpeed.MustGetNull()
	}
	if !s.CruisingLevel.IsUnset() {
		t.CruisingLevel = s.CruisingLevel.MustGetNull()
	}
	if !s.RouteText.IsUnset() {
		t.RouteText = s.RouteText.MustGetNull()
	}
	if !s.TotalElapsedTime.IsUnset() {
		t.TotalElapsedTime = s.TotalElapsedTime.MustGetNull()
	}
	if !s.FirEstimates.IsUnset() {
		t.FirEstimates = s.FirEstimates.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *FlightRouteVersionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return FlightRouteVersions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 10)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.FlightID.IsValue() {
			vals[1] = psql.Arg(s.FlightID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Version.IsValue() {
			vals[2] = psql.Arg(s.Version.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.FlightRules.IsUnset() {
			vals[3] = psql.Arg(s.FlightRules.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.CruisingSpeed.IsUnset() {
			vals[4] = psql.Arg(s.CruisingSpeed.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.CruisingLevel.IsUnset() {
			vals[5] = psql.Arg(s.CruisingLevel.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.RouteText.IsUnset() {
			vals[6] = psql.Arg(s.RouteText.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.TotalElapsedTime.IsUnset() {
			vals[7] = psql.Arg(s.TotalElapsedTime.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.FirEstimates.IsUnset() {
			vals[8] = psql.Arg(s.FirEstimates.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[9] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s FlightRouteVersionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s FlightRouteVersionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.FlightID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "flight_id")...),
			psql.Arg(s.FlightID),
		}})
	}

	if s.Version.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "version")...),
			psql.Arg(s.Version),
		}})
	}

	if !s.FlightRules.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "flight_rules")...),
			psql.Arg(s.FlightRules),
		}})
	}

	if !s.CruisingSpeed.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "cruising_speed")...),
			psql.Arg(s.CruisingSpeed),
		}})
	}

	if !s.CruisingLevel.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "cruising_level")...),
			psql.Arg(s.CruisingLevel),
		}})
	}

	if !s.RouteText.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "route_text")...),
			psql.Arg(s.RouteText),
		}})
	}

	if !s.TotalElapsedTime.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "total_elapsed_time")...),
			psql.Arg(s.TotalElapsedTime),
		}})
	}

	if !s.FirEstimates.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "fir_estimates")...),
			psql.Arg(s.FirEstimates),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindFlightRouteVersion retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindFlightRouteVersion(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*FlightRouteVersion, error) {
	if len(cols) == 0 {
		return FlightRouteVersions.Query(
			sm.Where(FlightRouteVersions.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return FlightRouteVersions.Query(
		sm.Where(FlightRouteVersions.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(FlightRouteVersions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// FlightRouteVersionExists checks the presence of a single record by primary key
func FlightRouteVersionExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return FlightRouteVersions.Query(
		sm.Where(FlightRouteVersions.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after FlightRouteVersion is retrieved from the database
func (o *FlightRouteVersion) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = FlightRouteVersions.AfterSelectHooks.RunHooks(ctx, exec, FlightRouteVersionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = FlightRouteVersions.AfterInsertHooks.RunHooks(ctx, exec, FlightRouteVersionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = FlightRouteVersions.AfterUpdateHooks.RunHooks(ctx, exec, FlightRouteVersionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = FlightRouteVersions.AfterDeleteHooks.RunHooks(ctx, exec, FlightRouteVersionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the FlightRouteVersion
func (o *FlightRouteVersion) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *FlightRouteVersion) pkEQ() dialect.Expression {
	return psql.Quote("flight_route_versions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the FlightRouteVersion
func (o *FlightRouteVersion) Update(ctx context.Context, exec bob.Executor, s *FlightRouteVersionSetter) error {
	v, err := FlightRouteVersions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single FlightRouteVersion record with an executor
func (o *FlightRouteVersion) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := FlightRouteVersions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the FlightRouteVersion using the executor
func (o *FlightRouteVersion) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := FlightRouteVersions.Query(
		sm.Where(FlightRouteVersions.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after FlightRouteVersionSlice is retrieved from the database
func (o FlightRouteVersionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = FlightRouteVersions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = FlightRouteVersions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = FlightRouteVersions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = FlightRouteVersions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o FlightRouteVersionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("flight_route_versions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o FlightRouteVersionSlice) copyMatchingRows(from ...*FlightRouteVersion) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o FlightRouteVersionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return FlightRouteVersions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *FlightRouteVersion:
				o.copyMatchingRows(retrieved)
			case []*FlightRouteVersion:
				o.copyMatchingRows(retrieved...)
			case FlightRouteVersionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a FlightRouteVersion or a slice of FlightRouteVersion
				// then run the AfterUpdateHooks on the slice
				_, err = FlightRouteVersions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o FlightRouteVersionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return FlightRouteVersions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *FlightRouteVersion:
				o.copyMatchingRows(retrieved)
			case []*FlightRouteVersion:
				o.copyMatchingRows(retrieved...)
			case FlightRouteVersionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a FlightRouteVersion or a slice of FlightRouteVersion
				// then run the AfterDeleteHooks on the slice
				_, err = FlightRouteVersions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o FlightRouteVersionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals FlightRouteVersionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := FlightRouteVersions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o FlightRouteVersionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := FlightRouteVersions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o FlightRouteVersionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := FlightRouteVersions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// RouteVersionFlightRouteElements starts a query for related objects on flight_route_elements
func (o *FlightRouteVersion) RouteVersionFlightRouteElements(mods ...bob.Mod[*dialect.SelectQuery]) FlightRouteElementsQuery {
	return FlightRouteElements.Query(append(mods,
		sm.Where(FlightRouteElements.Columns.RouteVersionID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os FlightRouteVersionSlice) RouteVersionFlightRouteElements(mods ...bob.Mod[*dialect.SelectQuery]) FlightRouteElementsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return FlightRouteElements.Query(append(mods,
		sm.Where(psql.Group(FlightRouteElements.Columns.RouteVersionID).OP("IN", PKArgExpr)),
	)...)
}

// Flight starts a query for related objects on flights
func (o *FlightRouteVersion) Flight(mods ...bob.Mod[*dialect.SelectQuery]) FlightsQuery {
	return Flights.Query(append(mods,
		sm.Where(Flights.Columns.ID.EQ(psql.Arg(o.FlightID))),
	)...)
}

func (os FlightRouteVersionSlice) Flight(mods ...bob.Mod[*dialect.SelectQuery]) FlightsQuery {
	pkFlightID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkFlightID = append(pkFlightID, o.FlightID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkFlightID), "uuid[]")),
	))

	return Flights.Query(append(mods,
		sm.Where(psql.Group(Flights.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertFlightRouteVersionRouteVersionFlightRouteElements0(ctx context.Context, exec bob.Executor, flightRouteElements1 []*FlightRouteElementSetter, flightRouteVersion0 *FlightRouteVersion) (FlightRouteElementSlice, error) {
	for i := range flightRouteElements1 {
		flightRouteElements1[i].RouteVersionID = omit.From(flightRouteVersion0.ID)
	}

	ret, err := FlightRouteElements.Insert(bob.ToMods(flightRouteElements1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertFlightRouteVersionRouteVersionFlightRouteElements0: %w", err)
	}

	return ret, nil
}

func attachFlightRouteVersionRouteVersionFlightRouteElements0(ctx context.Context, exec bob.Executor, count int, flightRouteElements1 FlightRouteElementSlice, flightRouteVersion0 *FlightRouteVersion) (FlightRouteElementSlice, error) {
	setter := &FlightRouteElementSetter{
		RouteVersionID: omit.From(flightRouteVersion0.ID),
	}

	err := flightRouteElements1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachFlightRouteVersionRouteVersionFlightRouteElements0: %w", err)
	}

	return flightRouteElements1, nil
}

func (flightRouteVersion0 *FlightRouteVersion) InsertRouteVersionFlightRouteElements(ctx context.Context, exec bob.Executor, related ...*FlightRouteElementSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	flightRouteElements1, err := insertFlightRouteVersionRouteVersionFlightRouteElements0(ctx, exec, related, flightRouteVersion0)
	if err != nil {
		return err
	}

	flightRouteVersion0.R.RouteVersionFlightRouteElements = append(flightRouteVersion0.R.RouteVersionFlightRouteElements, flightRouteElements1...)

	for _, rel := range flightRouteElements1 {
		rel.R.RouteVersionFlightRouteVersion = flightRouteVersion0
	}
	return nil
}

func (flightRouteVersion0 *FlightRouteVersion) AttachRouteVersionFlightRouteElements(ctx context.Context, exec bob.Executor, related ...*FlightRouteElement) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	flightRouteElements1 := FlightRouteElementSlice(related)

	_, err = attachFlightRouteVersionRouteVersionFlightRouteElements0(ctx, exec, len(related), flightRouteElements1, flightRouteVersion0)
	if err != nil {
		return err
	}

	flightRouteVersion0.R.RouteVersionFlightRouteElements = append(flightRouteVersion0.R.RouteVersionFlightRouteElements, flightRouteElements1...)

	for _, rel := range related {
		rel.R.RouteVersionFlightRouteVersion = flightRouteVersion0
	}

	return nil
}

func attachFlightRouteVersionFlight0(ctx context.Context, exec bob.Executor, count int, flightRouteVersion0 *FlightRouteVersion, flight1 *Flight) (*FlightRouteVersion, error) {
	setter := &FlightRouteVersionSetter{
		FlightID: omit.From(flight1.ID),
	}

	err := flightRouteVersion0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachFlightRouteVersionFlight0: %w", err)
	}

	return flightRouteVersion0, nil
}

func (flightRouteVersion0 *FlightRouteVersion) InsertFlight(ctx context.Context, exec bob.Executor, related *FlightSetter) error {
	var err error

	flight1, err := Flights.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachFlightRouteVersionFlight0(ctx, exec, 1, flightRouteVersion0, flight1)
	if err != nil {
		return err
	}

	flightRouteVersion0.R.Flight = flight1

	flight1.R.FlightRouteVersions = append(flight1.R.FlightRouteVersions, flightRouteVersion0)

	return nil
}

func (flightRouteVersion0 *FlightRouteVersion) AttachFlight(ctx context.Context, exec bob.Executor, flight1 *Flight) error {
	var err error

	_, err = attachFlightRouteVersionFlight0(ctx, exec, 1, flightRouteVersion0, flight1)
	if err != nil {
		return err
	}

	flightRouteVersion0.R.Flight = flight1

	flight1.R.FlightRouteVersions = append(flight1.R.FlightRouteVersions, flightRouteVersion0)

	return nil
}

type flightRouteVersionWhere[Q psql.Filterable] struct {
	ID               psql.WhereMod[Q, uuid.UUID]
	FlightID         psql.WhereMod[Q, uuid.UUID]
	Version          psql.WhereMod[Q, int32]
	FlightRules      psql.WhereNullMod[Q, string]
	CruisingSpeed    psql.WhereNullMod[Q, string]
	CruisingLevel    psql.WhereNullMod[Q, string]
	RouteText        psql.WhereNullMod[Q, string]
	TotalElapsedTime psql.WhereNullMod[Q, string]
	FirEstimates     psql.WhereNullMod[Q, pq.StringArray]
	CreatedAt        psql.WhereMod[Q, time.Time]
}

func (flightRouteVersionWhere[Q]) AliasedAs(alias string) flightRouteVersionWhere[Q] {
	return buildFlightRouteVersionWhere[Q](buildFlightRouteVersionColumns(alias))
}

func buildFlightRouteVersionWhere[Q psql.Filterable](cols flightRouteVersionColumns) flightRouteVersionWhere[Q] {
	return flightRouteVersionWhere[Q]{
		ID:               psql.Where[Q, uuid.UUID](cols.ID),
		FlightID:         psql.Where[Q, uuid.UUID](cols.FlightID),
		Version:          psql.Where[Q, int32](cols.Version),
		FlightRules:      psql.WhereNull[Q, string](cols.FlightRules),
		CruisingSpeed:    psql.WhereNull[Q, string](cols.CruisingSpeed),
		CruisingLevel:    psql.WhereNull[Q, string](cols.CruisingLevel),
		RouteText:        psql.WhereNull[Q, string](cols.RouteText),
		TotalElapsedTime: psql.WhereNull[Q, string](cols.TotalElapsedTime),
		FirEstimates:     psql.WhereNull[Q, pq.StringArray](cols.FirEstimates),
		CreatedAt:        psql.Where[Q, time.Time](cols.CreatedAt),
	}
}

func (o *FlightRouteVersion) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "RouteVersionFlightRouteElements":
		rels, ok := retrieved.(FlightRouteElementSlice)
		if !ok {
			return fmt.Errorf("flightRouteVersion cannot load %T as %q", retrieved, name)
		}

		o.R.RouteVersionFlightRouteElements = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.RouteVersionFlightRouteVersion = o
			}
		}
		return nil
	case "Flight":
		rel, ok := retrieved.(*Flight)
		if !ok {
			return fmt.Errorf("flightRouteVersion cannot load %T as %q", retrieved, name)
		}

		o.R.Flight = rel

		if rel != nil {
			rel.R.FlightRouteVersions = FlightRouteVersionSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("flightRouteVersion has no relationship %q", name)
	}
}

type flightRouteVersionPreloader struct {
	Flight func(...psql.PreloadOption) psql.Preloader
}

func buildFlightRouteVersionPreloader() flightRouteVersionPreloader {
	return flightRouteVersionPreloader{
		Flight: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Flight, FlightSlice](psql.PreloadRel{
				Name: "Flight",
				Sides: []psql.PreloadSide{
					{
						From:        FlightRouteVersions,
						To:          Flights,
						FromColumns: []string{"flight_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Flights.Columns.Names(), opts...)
		},
	}
}

type flightRouteVersionThenLoader[Q orm.Loadable] struct {
	RouteVersionFlightRouteElements func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Flight                          func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildFlightRouteVersionThenLoader[Q orm.Loadable]() flightRouteVersionThenLoader[Q] {
	type RouteVersionFlightRouteElementsLoadInterface interface {
		LoadRouteVersionFlightRouteElements(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type FlightLoadInterface interface {
		LoadFlight(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return flightRouteVersionThenLoader[Q]{
		RouteVersionFlightRouteElements: thenLoadBuilder[Q](
			"RouteVersionFlightRouteElements",
			func(ctx context.Context, exec bob.Executor, retrieved RouteVersionFlightRouteElementsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadRouteVersionFlightRouteElements(ctx, exec, mods...)
			},
		),
		Flight: thenLoadBuilder[Q](
			"Flight",
			func(ctx context.Context, exec bob.Executor, retrieved FlightLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadFlight(ctx, exec, mods...)
			},
		),
	}
}

// LoadRouteVersionFlightRouteElements loads the flightRouteVersion's RouteVersionFlightRouteElements into the .R struct
func (o *FlightRouteVersion) LoadRouteVersionFlightRouteElements(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.RouteVersionFlightRouteElements = nil

	related, err := o.RouteVersionFlightRouteElements(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.RouteVersionFlightRouteVersion = o
	}

	o.R.RouteVersionFlightRouteElements = related
	return nil
}

// LoadRouteVersionFlightRouteElements loads the flightRouteVersion's RouteVersionFlightRouteElements into the .R struct
func (os FlightRouteVersionSlice) LoadRouteVersionFlightRouteElements(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	flightRouteElements, err := os.RouteVersionFlightRouteElements(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.RouteVersionFlightRouteElements = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range flightRouteElements {

			if !(o.ID == rel.RouteVersionID) {
				continue
			}

			rel.R.RouteVersionFlightRouteVersion = o

			o.R.RouteVersionFlightRouteElements = append(o.R.RouteVersionFlightRouteElements, rel)
		}
	}

	return nil
}

// LoadFlight loads the flightRouteVersion's Flight into the .R struct
func (o *FlightRouteVersion) LoadFlight(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Flight = nil

	related, err := o.Flight(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.FlightRouteVersions = FlightRouteVersionSlice{o}

	o.R.Flight = related
	return nil
}

// LoadFlight loads the flightRouteVersion's Flight into the .R struct
func (os FlightRouteVersionSlice) LoadFlight(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	flights, err := os.Flight(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range flights {

			if !(o.FlightID == rel.ID) {
				continue
			}

			rel.R.FlightRouteVersions = append(rel.R.FlightRouteVersions, o)

			o.R.Flight = rel
			break
		}
	}

	return nil
}

type flightRouteVersionJoins[Q dialect.Joinable] struct {
	typ                             string
	RouteVersionFlightRouteElements modAs[Q, flightRouteElementColumns]
	Flight                          modAs[Q, flightColumns]
}

func (j flightRouteVersionJoins[Q]) aliasedAs(alias string) flightRouteVersionJoins[Q] {
	return buildFlightRouteVersionJoins[Q](buildFlightRouteVersionColumns(alias), j.typ)
}

func buildFlightRouteVersionJoins[Q dialect.Joinable](cols flightRouteVersionColumns, typ string) flightRouteVersionJoins[Q] {
	return flightRouteVersionJoins[Q]{
		typ: typ,
		RouteVersionFlightRouteElements: modAs[Q, flightRouteElementColumns]{
			c: FlightRouteElements.Columns,
			f: func(to flightRouteElementColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, FlightRouteElements.Name().As(to.Alias())).On(
						to.RouteVersionID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Flight: modAs[Q, flightColumns]{
			c: Flights.Columns,
			f: func(to flightColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Flights.Name().As(to.Alias())).On(
						to.ID.EQ(cols.FlightID),
					))
				}

				return mods
			},
		},
	}
}
