// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// FlightRouteElement is an object representing the database table.
type FlightRouteElement struct {
	ID             uuid.UUID        `db:"id,pk" `
	RouteVersionID uuid.UUID        `db:"route_version_id" `
	SeqNum         int32            `db:"seq_num" `
	WaypointName   string           `db:"waypoint_name" `
	Airway         null.Val[string] `db:"airway" `
	AirwayType     null.Val[string] `db:"airway_type" `
	ChangeSpeed    null.Val[string] `db:"change_speed" `
	ChangeLevel    null.Val[string] `db:"change_level" `

	R flightRouteElementR `db:"-" `
}

// FlightRouteElementSlice is an alias for a slice of pointers to FlightRouteElement.
// This should almost always be used instead of []*FlightRouteElement.
type FlightRouteElementSlice []*FlightRouteElement

// FlightRouteElements contains methods to work with the flight_route_elements table
var FlightRouteElements = psql.NewTablex[*FlightRouteElement, FlightRouteElementSlice, *FlightRouteElementSetter]("", "flight_route_elements", buildFlightRouteElementColumns("flight_route_elements"))

// FlightRouteElementsQuery is a query on the flight_route_elements table
type FlightRouteElementsQuery = *psql.ViewQuery[*FlightRouteElement, FlightRouteElementSlice]

// flightRouteElementR is where relationships are stored.
type flightRouteElementR struct {
	RouteVersionFlightRouteVersion *FlightRouteVersion // flight_route_elements.flight_route_elements_route_version_id_fkey
}

func buildFlightRouteElementColumns(alias string) flightRouteElementColumns {
	return flightRouteElementColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "route_version_id", "seq_num", "waypoint_name", "airway", "airway_type", "change_speed", "change_level",
		).WithParent("flight_route_elements"),
		tableAlias:     alias,
		ID:             psql.Quote(alias, "id"),
		RouteVersionID: psql.Quote(alias, "route_version_id"),
		SeqNum:         psql.Quote(alias, "seq_num"),
		WaypointName:   psql.Quote(alias, "waypoint_name"),
		Airway:         psql.Quote(alias, "airway"),
		AirwayType:     psql.Quote(alias, "airway_type"),
		ChangeSpeed:    psql.Quote(alias, "change_speed"),
		ChangeLevel:    psql.Quote(alias, "change_level"),
	}
}

type flightRouteElementColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             psql.Expression
	RouteVersionID psql.Expression
	SeqNum         psql.Expression
	WaypointName   psql.Expression
	Airway         psql.Expression
	AirwayType     psql.Expression
	ChangeSpeed    psql.Expression
	ChangeLevel    psql.Expression
}

func (c flightRouteElementColumns) Alias() string {
	return c.tableAlias
}

func (flightRouteElementColumns) AliasedAs(alias string) flightRouteElementColumns {
	return buildFlightRouteElementColumns(alias)
}

// FlightRouteElementSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type FlightRouteElementSetter struct {
	ID             omit.Val[uuid.UUID]  `db:"id,pk" `
	RouteVersionID omit.Val[uuid.UUID]  `db:"route_version_id" `
	SeqNum         omit.Val[int32]      `db:"seq_num" `
	WaypointName   omit.Val[string]     `db:"waypoint_name" `
	Airway         omitnull.Val[string] `db:"airway" `
	AirwayType     omitnull.Val[string] `db:"airway_type" `
	ChangeSpeed    omitnull.Val[string] `db:"change_speed" `
	ChangeLevel    omitnull.Val[string] `db:"change_level" `
}

func (s FlightRouteElementSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.RouteVersionID.IsValue() {
		vals = append(vals, "route_version_id")
	}
	if s.SeqNum.IsValue() {
		vals = append(vals, "seq_num")
	}
	if s.WaypointName.IsValue() {
		vals = append(vals, "waypoint_name")
	}
	if !s.Airway.IsUnset() {
		vals = append(vals, "airway")
	}
	if !s.AirwayType.IsUnset() {
		vals = append(vals, "airway_type")
	}
	if !s.ChangeSpeed.IsUnset() {
		vals = append(vals, "change_speed")
	}
	if !s.ChangeLevel.IsUnset() {
		vals = append(vals, "change_level")
	}
	return vals
}

func (s FlightRouteElementSetter) Overwrite(t *FlightRouteElement) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.RouteVersionID.IsValue() {
		t.RouteVersionID = s.RouteVersionID.MustGet()
	}
	if s.SeqNum.IsValue() {
		t.SeqNum = s.SeqNum.MustGet()
	}
	if s.WaypointName.IsValue() {
		t.WaypointName = s.WaypointName.MustGet()
	}
	if !s.Airway.IsUnset() {
		t.Airway = s.Airway.MustGetNull()
	}
	if !s.AirwayType.IsUnset() {
		t.AirwayType = s.AirwayType.MustGetNull()
	}
	if !s.ChangeSpeed.IsUnset() {
		t.ChangeSpeed = s.ChangeSpeed.MustGetNull()
	}
	if !s.ChangeLevel.IsUnset() {
		t.ChangeLevel = s.ChangeLevel.MustGetNull()
	}
}

func (s *FlightRouteElementSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return FlightRouteElements.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.RouteVersionID.IsValue() {
			vals[1] = psql.Arg(s.RouteVersionID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.SeqNum.IsValue() {
			vals[2] = psql.Arg(s.SeqNum.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.WaypointName.IsValue() {
			vals[3] = psql.Arg(s.WaypointName.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Airway.IsUnset() {
			vals[4] = psql.Arg(s.Airway.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.AirwayType.IsUnset() {
			vals[5] = psql.Arg(s.AirwayType.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.ChangeSpeed.IsUnset() {
			vals[6] = psql.Arg(s.ChangeSpeed.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.ChangeLevel.IsUnset() {
			vals[7] = psql.Arg(s.ChangeLevel.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s FlightRouteElementSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s FlightRouteElementSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.RouteVersionID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "route_version_id")...),
			psql.Arg(s.RouteVersionID),
		}})
	}

	if s.SeqNum.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "seq_num")...),
			psql.Arg(s.SeqNum),
		}})
	}

	if s.WaypointName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "waypoint_name")...),
			psql.Arg(s.WaypointName),
		}})
	}

	if !s.Airway.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "airway")...),
			psql.Arg(s.Airway),
		}})
	}

	if !s.AirwayType.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "airway_type")...),
			psql.Arg(s.AirwayType),
		}})
	}

	if !s.ChangeSpeed.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "change_speed")...),
			psql.Arg(s.ChangeSpeed),
		}})
	}

	if !s.ChangeLevel.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "change_level")...),
			psql.Arg(s.ChangeLevel),
		}})
	}

	return exprs
}

// FindFlightRouteElement retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindFlightRouteElement(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*FlightRouteElement, error) {
	if len(cols) == 0 {
		return FlightRouteElements.Query(
			sm.Where(FlightRouteElements.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return FlightRouteElements.Query(
		sm.Where(FlightRouteElements.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(FlightRouteElements.Columns.Only(cols...)),
	).One(ctx, exec)
}

// FlightRouteElementExists checks the presence of a single record by primary key
func FlightRouteElementExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return FlightRouteElements.Query(
		sm.Where(FlightRouteElements.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after FlightRouteElement is retrieved from the database
func (o *FlightRouteElement) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = FlightRouteElements.AfterSelectHooks.RunHooks(ctx, exec, FlightRouteElementSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = FlightRouteElements.AfterInsertHooks.RunHooks(ctx, exec, FlightRouteElementSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = FlightRouteElements.AfterUpdateHooks.RunHooks(ctx, exec, FlightRouteElementSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = FlightRouteElements.AfterDeleteHooks.RunHooks(ctx, exec, FlightRouteElementSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the FlightRouteElement
func (o *FlightRouteElement) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *FlightRouteElement) pkEQ() dialect.Expression {
	return psql.Quote("flight_route_elements", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the FlightRouteElement
func (o *FlightRouteElement) Update(ctx context.Context, exec bob.Executor, s *FlightRouteElementSetter) error {
	v, err := FlightRouteElements.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single FlightRouteElement record with an executor
func (o *FlightRouteElement) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := FlightRouteElements.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the FlightRouteElement using the executor
func (o *FlightRouteElement) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := FlightRouteElements.Query(
		sm.Where(FlightRouteElements.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after FlightRouteElementSlice is retrieved from the database
func (o FlightRouteElementSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = FlightRouteElements.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = FlightRouteElements.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = FlightRouteElements.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = FlightRouteElements.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o FlightRouteElementSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("flight_route_elements", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o FlightRouteElementSlice) copyMatchingRows(from ...*FlightRouteElement) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o FlightRouteElementSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return FlightRouteElements.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *FlightRouteElement:
				o.copyMatchingRows(retrieved)
			case []*FlightRouteElement:
				o.copyMatchingRows(retrieved...)
			case FlightRouteElementSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a FlightRouteElement or a slice of FlightRouteElement
				// then run the AfterUpdateHooks on the slice
				_, err = FlightRouteElements.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o FlightRouteElementSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return FlightRouteElements.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *FlightRouteElement:
				o.copyMatchingRows(retrieved)
			case []*FlightRouteElement:
				o.copyMatchingRows(retrieved...)
			case FlightRouteElementSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a FlightRouteElement or a slice of FlightRouteElement
				// then run the AfterDeleteHooks on the slice
				_, err = FlightRouteElements.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o FlightRouteElementSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals FlightRouteElementSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := FlightRouteElements.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o FlightRouteElementSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := FlightRouteElements.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o FlightRouteElementSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := FlightRouteElements.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// RouteVersionFlightRouteVersion starts a query for related objects on flight_route_versions
func (o *FlightRouteElement) RouteVersionFlightRouteVersion(mods ...bob.Mod[*dialect.SelectQuery]) FlightRouteVersionsQuery {
	return FlightRouteVersions.Query(append(mods,
		sm.Where(FlightRouteVersions.Columns.ID.EQ(psql.Arg(o.RouteVersionID))),
	)...)
}

func (os FlightRouteElementSlice) RouteVersionFlightRouteVersion(mods ...bob.Mod[*dialect.SelectQuery]) FlightRouteVersionsQuery {
	pkRouteVersionID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkRouteVersionID = append(pkRouteVersionID, o.RouteVersionID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkRouteVersionID), "uuid[]")),
	))

	return FlightRouteVersions.Query(append(mods,
		sm.Where(psql.Group(FlightRouteVersions.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachFlightRouteElementRouteVersionFlightRouteVersion0(ctx context.Context, exec bob.Executor, count int, flightRouteElement0 *FlightRouteElement, flightRouteVersion1 *FlightRouteVersion) (*FlightRouteElement, error) {
	setter := &FlightRouteElementSetter{
		RouteVersionID: omit.From(flightRouteVersion1.ID),
	}

	err := flightRouteElement0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachFlightRouteElementRouteVersionFlightRouteVersion0: %w", err)
	}

	return flightRouteElement0, nil
}

func (flightRouteElement0 *FlightRouteElement) InsertRouteVersionFlightRouteVersion(ctx context.Context, exec bob.Executor, related *FlightRouteVersionSetter) error {
	var err error

	flightRouteVersion1, err := FlightRouteVersions.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachFlightRouteElementRouteVersionFlightRouteVersion0(ctx, exec, 1, flightRouteElement0, flightRouteVersion1)
	if err != nil {
		return err
	}

	flightRouteElement0.R.RouteVersionFlightRouteVersion = flightRouteVersion1

	flightRouteVersion1.R.RouteVersionFlightRouteElements = append(flightRouteVersion1.R.RouteVersionFlightRouteElements, flightRouteElement0)

	return nil
}

func (flightRouteElement0 *FlightRouteElement) AttachRouteVersionFlightRouteVersion(ctx context.Context, exec bob.Executor, flightRouteVersion1 *FlightRouteVersion) error {
	var err error

	_, err = attachFlightRouteElementRouteVersionFlightRouteVersion0(ctx, exec, 1, flightRouteElement0, flightRouteVersion1)
	if err != nil {
		return err
	}

	flightRouteElement0.R.RouteVersionFlightRouteVersion = flightRouteVersion1

	flightRouteVersion1.R.RouteVersionFlightRouteElements = append(flightRouteVersion1.R.RouteVersionFlightRouteElements, flightRouteElement0)

	return nil
}

type flightRouteElementWhere[Q psql.Filterable] struct {
	ID             psql.WhereMod[Q, uuid.UUID]
	RouteVersionID psql.WhereMod[Q, uuid.UUID]
	SeqNum         psql.WhereMod[Q, int32]
	WaypointName   psql.WhereMod[Q, string]
	Airway         psql.WhereNullMod[Q, string]
	AirwayType     psql.WhereNullMod[Q, string]
	ChangeSpeed    psql.WhereNullMod[Q, string]
	ChangeLevel    psql.WhereNullMod[Q, string]
}

func (flightRouteElementWhere[Q]) AliasedAs(alias string) flightRouteElementWhere[Q] {
	return buildFlightRouteElementWhere[Q](buildFlightRouteElementColumns(alias))
}

func buildFlightRouteElementWhere[Q psql.Filterable](cols flightRouteElementColumns) flightRouteElementWhere[Q] {
	return flightRouteElementWhere[Q]{
		ID:             psql.Where[Q, uuid.UUID](cols.ID),
		RouteVersionID: psql.Where[Q, uuid.UUID](cols.RouteVersionID),
		SeqNum:         psql.Where[Q, int32](cols.SeqNum),
		WaypointName:   psql.Where[Q, string](cols.WaypointName),
		Airway:         psql.WhereNull[Q, string](cols.Airway),
		AirwayType:     psql.WhereNull[Q, string](cols.AirwayType),
		ChangeSpeed:    psql.WhereNull[Q, string](cols.ChangeSpeed),
		ChangeLevel:    psql.WhereNull[Q, string](cols.ChangeLevel),
	}
}

func (o *FlightRouteElement) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "RouteVersionFlightRouteVersion":
		rel, ok := retrieved.(*FlightRouteVersion)
		if !ok {
			return fmt.Errorf("flightRouteElement cannot load %T as %q", retrieved, name)
		}

		o.R.RouteVersionFlightRouteVersion = rel

		if rel != nil {
			rel.R.RouteVersionFlightRouteElements = FlightRouteElementSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("flightRouteElement has no relationship %q", name)
	}
}

type flightRouteElementPreloader struct {
	RouteVersionFlightRouteVersion func(...psql.PreloadOption) psql.Preloader
}

func buildFlightRouteElementPreloader() flightRouteElementPreloader {
	return flightRouteElementPreloader{
		RouteVersionFlightRouteVersion: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*FlightRouteVersion, FlightRouteVersionSlice](psql.PreloadRel{
				Name: "RouteVersionFlightRouteVersion",
				Sides: []psql.PreloadSide{
					{
						From:        FlightRouteElements,
						To:          FlightRouteVersions,
						FromColumns: []string{"route_version_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, FlightRouteVersions.Columns.Names(), opts...)
		},
	}
}

type flightRouteElementThenLoader[Q orm.Loadable] struct {
	RouteVersionFlightRouteVersion func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildFlightRouteElementThenLoader[Q orm.Loadable]() flightRouteElementThenLoader[Q] {
	type RouteVersionFlightRouteVersionLoadInterface interface {
		LoadRouteVersionFlightRouteVersion(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return flightRouteElementThenLoader[Q]{
		RouteVersionFlightRouteVersion: thenLoadBuilder[Q](
			"RouteVersionFlightRouteVersion",
			func(ctx context.Context, exec bob.Executor, retrieved RouteVersionFlightRouteVersionLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadRouteVersionFlightRouteVersion(ctx, exec, mods...)
			},
		),
	}
}

// LoadRouteVersionFlightRouteVersion loads the flightRouteElement's RouteVersionFlightRouteVersion into the .R struct
func (o *FlightRouteElement) LoadRouteVersionFlightRouteVersion(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.RouteVersionFlightRouteVersion = nil

	related, err := o.RouteVersionFlightRouteVersion(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.RouteVersionFlightRouteElements = FlightRouteElementSlice{o}

	o.R.RouteVersionFlightRouteVersion = related
	return nil
}

// LoadRouteVersionFlightRouteVersion loads the flightRouteElement's RouteVersionFlightRouteVersion into the .R struct
func (os FlightRouteElementSlice) LoadRouteVersionFlightRouteVersion(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	flightRouteVersions, err := os.RouteVersionFlightRouteVersion(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range flightRouteVersions {

			if !(o.RouteVersionID == rel.ID) {
				continue
			}

			rel.R.RouteVersionFlightRouteElements = append(rel.R.RouteVersionFlightRouteElements, o)

			o.R.RouteVersionFlightRouteVersion = rel
			break
		}
	}

	return nil
}

type flightRouteElementJoins[Q dialect.Joinable] struct {
	typ                            string
	RouteVersionFlightRouteVersion modAs[Q, flightRouteVersionColumns]
}

func (j flightRouteElementJoins[Q]) aliasedAs(alias string) flightRouteElementJoins[Q] {
	return buildFlightRouteElementJoins[Q](buildFlightRouteElementColumns(alias), j.typ)
}

func buildFlightRouteElementJoins[Q dialect.Joinable](cols flightRouteElementColumns, typ string) flightRouteElementJoins[Q] {
	return flightRouteElementJoins[Q]{
		typ: typ,
		RouteVersionFlightRouteVersion: modAs[Q, flightRouteVersionColumns]{
			c: FlightRouteVersions.Columns,
			f: func(to flightRouteVersionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, FlightRouteVersions.Name().As(to.Alias())).On(
						to.ID.EQ(cols.RouteVersionID),
					))
				}

				return mods
			},
		},
	}
}
