// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// WaypointEdge is an object representing the database table.
type WaypointEdge struct {
	FromName  string  `db:"from_name,pk" `
	ToName    string  `db:"to_name,pk" `
	DistanceM float64 `db:"distance_m" `
}

// WaypointEdgeSlice is an alias for a slice of pointers to WaypointEdge.
// This should almost always be used instead of []*WaypointEdge.
type WaypointEdgeSlice []*WaypointEdge

// WaypointEdges contains methods to work with the waypoint_edges table
var WaypointEdges = psql.NewTablex[*WaypointEdge, WaypointEdgeSlice, *WaypointEdgeSetter]("", "waypoint_edges", buildWaypointEdgeColumns("waypoint_edges"))

// WaypointEdgesQuery is a query on the waypoint_edges table
type WaypointEdgesQuery = *psql.ViewQuery[*WaypointEdge, WaypointEdgeSlice]

func buildWaypointEdgeColumns(alias string) waypointEdgeColumns {
	return waypointEdgeColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"from_name", "to_name", "distance_m",
		).WithParent("waypoint_edges"),
		tableAlias: alias,
		FromName:   psql.Quote(alias, "from_name"),
		ToName:     psql.Quote(alias, "to_name"),
		DistanceM:  psql.Quote(alias, "distance_m"),
	}
}

type waypointEdgeColumns struct {
	expr.ColumnsExpr
	tableAlias string
	FromName   psql.Expression
	ToName     psql.Expression
	DistanceM  psql.Expression
}

func (c waypointEdgeColumns) Alias() string {
	return c.tableAlias
}

func (waypointEdgeColumns) AliasedAs(alias string) waypointEdgeColumns {
	return buildWaypointEdgeColumns(alias)
}

// WaypointEdgeSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type WaypointEdgeSetter struct {
	FromName  omit.Val[string]  `db:"from_name,pk" `
	ToName    omit.Val[string]  `db:"to_name,pk" `
	DistanceM omit.Val[float64] `db:"distance_m" `
}

func (s WaypointEdgeSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.FromName.IsValue() {
		vals = append(vals, "from_name")
	}
	if s.ToName.IsValue() {
		vals = append(vals, "to_name")
	}
	if s.DistanceM.IsValue() {
		vals = append(vals, "distance_m")
	}
	return vals
}

func (s WaypointEdgeSetter) Overwrite(t *WaypointEdge) {
	if s.FromName.IsValue() {
		t.FromName = s.FromName.MustGet()
	}
	if s.ToName.IsValue() {
		t.ToName = s.ToName.MustGet()
	}
	if s.DistanceM.IsValue() {
		t.DistanceM = s.DistanceM.MustGet()
	}
}

func (s *WaypointEdgeSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return WaypointEdges.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 3)
		if s.FromName.IsValue() {
			vals[0] = psql.Arg(s.FromName.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.ToName.IsValue() {
			vals[1] = psql.Arg(s.ToName.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.DistanceM.IsValue() {
			vals[2] = psql.Arg(s.DistanceM.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s WaypointEdgeSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s WaypointEdgeSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.FromName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "from_name")...),
			psql.Arg(s.FromName),
		}})
	}

	if s.ToName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "to_name")...),
			psql.Arg(s.ToName),
		}})
	}

	if s.DistanceM.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "distance_m")...),
			psql.Arg(s.DistanceM),
		}})
	}

	return exprs
}

// FindWaypointEdge retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindWaypointEdge(ctx context.Context, exec bob.Executor, FromNamePK string, ToNamePK string, cols ...string) (*WaypointEdge, error) {
	if len(cols) == 0 {
		return WaypointEdges.Query(
			sm.Where(WaypointEdges.Columns.FromName.EQ(psql.Arg(FromNamePK))),
			sm.Where(WaypointEdges.Columns.ToName.EQ(psql.Arg(ToNamePK))),
		).One(ctx, exec)
	}

	return WaypointEdges.Query(
		sm.Where(WaypointEdges.Columns.FromName.EQ(psql.Arg(FromNamePK))),
		sm.Where(WaypointEdges.Columns.ToName.EQ(psql.Arg(ToNamePK))),
		sm.Columns(WaypointEdges.Columns.Only(cols...)),
	).One(ctx, exec)
}

// WaypointEdgeExists checks the presence of a single record by primary key
func WaypointEdgeExists(ctx context.Context, exec bob.Executor, FromNamePK string, ToNamePK string) (bool, error) {
	return WaypointEdges.Query(
		sm.Where(WaypointEdges.Columns.FromName.EQ(psql.Arg(FromNamePK))),
		sm.Where(WaypointEdges.Columns.ToName.EQ(psql.Arg(ToNamePK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after WaypointEdge is retrieved from the database
func (o *WaypointEdge) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = WaypointEdges.AfterSelectHooks.RunHooks(ctx, exec, WaypointEdgeSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = WaypointEdges.AfterInsertHooks.RunHooks(ctx, exec, WaypointEdgeSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = WaypointEdges.AfterUpdateHooks.RunHooks(ctx, exec, WaypointEdgeSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = WaypointEdges.AfterDeleteHooks.RunHooks(ctx, exec, WaypointEdgeSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the WaypointEdge
func (o *WaypointEdge) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.FromName,
		o.ToName,
	)
}

func (o *WaypointEdge) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("waypoint_edges", "from_name"), psql.Quote("waypoint_edges", "to_name")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the WaypointEdge
func (o *WaypointEdge) Update(ctx context.Context, exec bob.Executor, s *WaypointEdgeSetter) error {
	v, err := WaypointEdges.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single WaypointEdge record with an executor
func (o *WaypointEdge) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := WaypointEdges.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the WaypointEdge using the executor
func (o *WaypointEdge) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := WaypointEdges.Query(
		sm.Where(WaypointEdges.Columns.FromName.EQ(psql.Arg(o.FromName))),
		sm.Where(WaypointEdges.Columns.ToName.EQ(psql.Arg(o.ToName))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after WaypointEdgeSlice is retrieved from the database
func (o WaypointEdgeSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = WaypointEdges.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = WaypointEdges.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = WaypointEdges.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = WaypointEdges.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o WaypointEdgeSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("waypoint_edges", "from_name"), psql.Quote("waypoint_edges", "to_name")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o WaypointEdgeSlice) copyMatchingRows(from ...*WaypointEdge) {
	for i, old := range o {
		for _, new := range from {
			if new.FromName != old.FromName {
				continue
			}
			if new.ToName != old.ToName {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o WaypointEdgeSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return WaypointEdges.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *WaypointEdge:
				o.copyMatchingRows(retrieved)
			case []*WaypointEdge:
				o.copyMatchingRows(retrieved...)
			case WaypointEdgeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a WaypointEdge or a slice of WaypointEdge
				// then run the AfterUpdateHooks on the slice
				_, err = WaypointEdges.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o WaypointEdgeSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return WaypointEdges.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *WaypointEdge:
				o.copyMatchingRows(retrieved)
			case []*WaypointEdge:
				o.copyMatchingRows(retrieved...)
			case WaypointEdgeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a WaypointEdge or a slice of WaypointEdge
				// then run the AfterDeleteHooks on the slice
				_, err = WaypointEdges.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o WaypointEdgeSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals WaypointEdgeSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := WaypointEdges.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o WaypointEdgeSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := WaypointEdges.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o WaypointEdgeSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := WaypointEdges.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type waypointEdgeWhere[Q psql.Filterable] struct {
	FromName  psql.WhereMod[Q, string]
	ToName    psql.WhereMod[Q, string]
	DistanceM psql.WhereMod[Q, float64]
}

func (waypointEdgeWhere[Q]) AliasedAs(alias string) waypointEdgeWhere[Q] {
	return buildWaypointEdgeWhere[Q](buildWaypointEdgeColumns(alias))
}

func buildWaypointEdgeWhere[Q psql.Filterable](cols waypointEdgeColumns) waypointEdgeWhere[Q] {
	return waypointEdgeWhere[Q]{
		FromName:  psql.Where[Q, string](cols.FromName),
		ToName:    psql.Where[Q, string](cols.ToName),
		DistanceM: psql.Where[Q, float64](cols.DistanceM),
	}
}
