// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// WaypointEdge is an object representing the database table.
type WaypointEdge struct {
	FromName  string  `db:"from_name,pk" `
	ToName    string  `db:"to_name,pk" `
	DistanceM float64 `db:"distance_m" `

	R waypointEdgeR `db:"-" `
}

// WaypointEdgeSlice is an alias for a slice of pointers to WaypointEdge.
// This should almost always be used instead of []*WaypointEdge.
type WaypointEdgeSlice []*WaypointEdge

// WaypointEdges contains methods to work with the waypoint_edges table
var WaypointEdges = psql.NewTablex[*WaypointEdge, WaypointEdgeSlice, *WaypointEdgeSetter]("", "waypoint_edges", buildWaypointEdgeColumns("waypoint_edges"))

// WaypointEdgesQuery is a query on the waypoint_edges table
type WaypointEdgesQuery = *psql.ViewQuery[*WaypointEdge, WaypointEdgeSlice]

// waypointEdgeR is where relationships are stored.
type waypointEdgeR struct {
	FromNameWaypoint *Waypoint // waypoint_edges.waypoint_edges_from_name_fkey
	ToNameWaypoint   *Waypoint // waypoint_edges.waypoint_edges_to_name_fkey
}

func buildWaypointEdgeColumns(alias string) waypointEdgeColumns {
	return waypointEdgeColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"from_name", "to_name", "distance_m",
		).WithParent("waypoint_edges"),
		tableAlias: alias,
		FromName:   psql.Quote(alias, "from_name"),
		ToName:     psql.Quote(alias, "to_name"),
		DistanceM:  psql.Quote(alias, "distance_m"),
	}
}

type waypointEdgeColumns struct {
	expr.ColumnsExpr
	tableAlias string
	FromName   psql.Expression
	ToName     psql.Expression
	DistanceM  psql.Expression
}

func (c waypointEdgeColumns) Alias() string {
	return c.tableAlias
}

func (waypointEdgeColumns) AliasedAs(alias string) waypointEdgeColumns {
	return buildWaypointEdgeColumns(alias)
}

// WaypointEdgeSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type WaypointEdgeSetter struct {
	FromName  omit.Val[string]  `db:"from_name,pk" `
	ToName    omit.Val[string]  `db:"to_name,pk" `
	DistanceM omit.Val[float64] `db:"distance_m" `
}

func (s WaypointEdgeSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.FromName.IsValue() {
		vals = append(vals, "from_name")
	}
	if s.ToName.IsValue() {
		vals = append(vals, "to_name")
	}
	if s.DistanceM.IsValue() {
		vals = append(vals, "distance_m")
	}
	return vals
}

func (s WaypointEdgeSetter) Overwrite(t *WaypointEdge) {
	if s.FromName.IsValue() {
		t.FromName = s.FromName.MustGet()
	}
	if s.ToName.IsValue() {
		t.ToName = s.ToName.MustGet()
	}
	if s.DistanceM.IsValue() {
		t.DistanceM = s.DistanceM.MustGet()
	}
}

func (s *WaypointEdgeSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return WaypointEdges.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 3)
		if s.FromName.IsValue() {
			vals[0] = psql.Arg(s.FromName.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.ToName.IsValue() {
			vals[1] = psql.Arg(s.ToName.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.DistanceM.IsValue() {
			vals[2] = psql.Arg(s.DistanceM.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s WaypointEdgeSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s WaypointEdgeSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.FromName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "from_name")...),
			psql.Arg(s.FromName),
		}})
	}

	if s.ToName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "to_name")...),
			psql.Arg(s.ToName),
		}})
	}

	if s.DistanceM.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "distance_m")...),
			psql.Arg(s.DistanceM),
		}})
	}

	return exprs
}

// FindWaypointEdge retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindWaypointEdge(ctx context.Context, exec bob.Executor, FromNamePK string, ToNamePK string, cols ...string) (*WaypointEdge, error) {
	if len(cols) == 0 {
		return WaypointEdges.Query(
			sm.Where(WaypointEdges.Columns.FromName.EQ(psql.Arg(FromNamePK))),
			sm.Where(WaypointEdges.Columns.ToName.EQ(psql.Arg(ToNamePK))),
		).One(ctx, exec)
	}

	return WaypointEdges.Query(
		sm.Where(WaypointEdges.Columns.FromName.EQ(psql.Arg(FromNamePK))),
		sm.Where(WaypointEdges.Columns.ToName.EQ(psql.Arg(ToNamePK))),
		sm.Columns(WaypointEdges.Columns.Only(cols...)),
	).One(ctx, exec)
}

// WaypointEdgeExists checks the presence of a single record by primary key
func WaypointEdgeExists(ctx context.Context, exec bob.Executor, FromNamePK string, ToNamePK string) (bool, error) {
	return WaypointEdges.Query(
		sm.Where(WaypointEdges.Columns.FromName.EQ(psql.Arg(FromNamePK))),
		sm.Where(WaypointEdges.Columns.ToName.EQ(psql.Arg(ToNamePK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after WaypointEdge is retrieved from the database
func (o *WaypointEdge) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = WaypointEdges.AfterSelectHooks.RunHooks(ctx, exec, WaypointEdgeSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = WaypointEdges.AfterInsertHooks.RunHooks(ctx, exec, WaypointEdgeSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = WaypointEdges.AfterUpdateHooks.RunHooks(ctx, exec, WaypointEdgeSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = WaypointEdges.AfterDeleteHooks.RunHooks(ctx, exec, WaypointEdgeSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the WaypointEdge
func (o *WaypointEdge) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.FromName,
		o.ToName,
	)
}

func (o *WaypointEdge) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("waypoint_edges", "from_name"), psql.Quote("waypoint_edges", "to_name")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the WaypointEdge
func (o *WaypointEdge) Update(ctx context.Context, exec bob.Executor, s *WaypointEdgeSetter) error {
	v, err := WaypointEdges.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single WaypointEdge record with an executor
func (o *WaypointEdge) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := WaypointEdges.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the WaypointEdge using the executor
func (o *WaypointEdge) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := WaypointEdges.Query(
		sm.Where(WaypointEdges.Columns.FromName.EQ(psql.Arg(o.FromName))),
		sm.Where(WaypointEdges.Columns.ToName.EQ(psql.Arg(o.ToName))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after WaypointEdgeSlice is retrieved from the database
func (o WaypointEdgeSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = WaypointEdges.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = WaypointEdges.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = WaypointEdges.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = WaypointEdges.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o WaypointEdgeSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("waypoint_edges", "from_name"), psql.Quote("waypoint_edges", "to_name")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o WaypointEdgeSlice) copyMatchingRows(from ...*WaypointEdge) {
	for i, old := range o {
		for _, new := range from {
			if new.FromName != old.FromName {
				continue
			}
			if new.ToName != old.ToName {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o WaypointEdgeSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return WaypointEdges.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *WaypointEdge:
				o.copyMatchingRows(retrieved)
			case []*WaypointEdge:
				o.copyMatchingRows(retrieved...)
			case WaypointEdgeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a WaypointEdge or a slice of WaypointEdge
				// then run the AfterUpdateHooks on the slice
				_, err = WaypointEdges.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o WaypointEdgeSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return WaypointEdges.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *WaypointEdge:
				o.copyMatchingRows(retrieved)
			case []*WaypointEdge:
				o.copyMatchingRows(retrieved...)
			case WaypointEdgeSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a WaypointEdge or a slice of WaypointEdge
				// then run the AfterDeleteHooks on the slice
				_, err = WaypointEdges.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o WaypointEdgeSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals WaypointEdgeSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := WaypointEdges.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o WaypointEdgeSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := WaypointEdges.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o WaypointEdgeSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := WaypointEdges.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// FromNameWaypoint starts a query for related objects on waypoints
func (o *WaypointEdge) FromNameWaypoint(mods ...bob.Mod[*dialect.SelectQuery]) WaypointsQuery {
	return Waypoints.Query(append(mods,
		sm.Where(Waypoints.Columns.Name.EQ(psql.Arg(o.FromName))),
	)...)
}

func (os WaypointEdgeSlice) FromNameWaypoint(mods ...bob.Mod[*dialect.SelectQuery]) WaypointsQuery {
	pkFromName := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkFromName = append(pkFromName, o.FromName)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkFromName), "character varying[]")),
	))

	return Waypoints.Query(append(mods,
		sm.Where(psql.Group(Waypoints.Columns.Name).OP("IN", PKArgExpr)),
	)...)
}

// ToNameWaypoint starts a query for related objects on waypoints
func (o *WaypointEdge) ToNameWaypoint(mods ...bob.Mod[*dialect.SelectQuery]) WaypointsQuery {
	return Waypoints.Query(append(mods,
		sm.Where(Waypoints.Columns.Name.EQ(psql.Arg(o.ToName))),
	)...)
}

func (os WaypointEdgeSlice) ToNameWaypoint(mods ...bob.Mod[*dialect.SelectQuery]) WaypointsQuery {
	pkToName := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkToName = append(pkToName, o.ToName)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkToName), "character varying[]")),
	))

	return Waypoints.Query(append(mods,
		sm.Where(psql.Group(Waypoints.Columns.Name).OP("IN", PKArgExpr)),
	)...)
}

func attachWaypointEdgeFromNameWaypoint0(ctx context.Context, exec bob.Executor, count int, waypointEdge0 *WaypointEdge, waypoint1 *Waypoint) (*WaypointEdge, error) {
	setter := &WaypointEdgeSetter{
		FromName: omit.From(waypoint1.Name),
	}

	err := waypointEdge0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachWaypointEdgeFromNameWaypoint0: %w", err)
	}

	return waypointEdge0, nil
}

func (waypointEdge0 *WaypointEdge) InsertFromNameWaypoint(ctx context.Context, exec bob.Executor, related *WaypointSetter) error {
	var err error

	waypoint1, err := Waypoints.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachWaypointEdgeFromNameWaypoint0(ctx, exec, 1, waypointEdge0, waypoint1)
	if err != nil {
		return err
	}

	waypointEdge0.R.FromNameWaypoint = waypoint1

	waypoint1.R.FromNameWaypointEdges = append(waypoint1.R.FromNameWaypointEdges, waypointEdge0)

	return nil
}

func (waypointEdge0 *WaypointEdge) AttachFromNameWaypoint(ctx context.Context, exec bob.Executor, waypoint1 *Waypoint) error {
	var err error

	_, err = attachWaypointEdgeFromNameWaypoint0(ctx, exec, 1, waypointEdge0, waypoint1)
	if err != nil {
		return err
	}

	waypointEdge0.R.FromNameWaypoint = waypoint1

	waypoint1.R.FromNameWaypointEdges = append(waypoint1.R.FromNameWaypointEdges, waypointEdge0)

	return nil
}

func attachWaypointEdgeToNameWaypoint0(ctx context.Context, exec bob.Executor, count int, waypointEdge0 *WaypointEdge, waypoint1 *Waypoint) (*WaypointEdge, error) {
	setter := &WaypointEdgeSetter{
		ToName: omit.From(waypoint1.Name),
	}

	err := waypointEdge0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachWaypointEdgeToNameWaypoint0: %w", err)
	}

	return waypointEdge0, nil
}

func (waypointEdge0 *WaypointEdge) InsertToNameWaypoint(ctx context.Context, exec bob.Executor, related *WaypointSetter) error {
	var err error

	waypoint1, err := Waypoints.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachWaypointEdgeToNameWaypoint0(ctx, exec, 1, waypointEdge0, waypoint1)
	if err != nil {
		return err
	}

	waypointEdge0.R.ToNameWaypoint = waypoint1

	waypoint1.R.ToNameWaypointEdges = append(waypoint1.R.ToNameWaypointEdges, waypointEdge0)

	return nil
}

func (waypointEdge0 *WaypointEdge) AttachToNameWaypoint(ctx context.Context, exec bob.Executor, waypoint1 *Waypoint) error {
	var err error

	_, err = attachWaypointEdgeToNameWaypoint0(ctx, exec, 1, waypointEdge0, waypoint1)
	if err != nil {
		return err
	}

	waypointEdge0.R.ToNameWaypoint = waypoint1

	waypoint1.R.ToNameWaypointEdges = append(waypoint1.R.ToNameWaypointEdges, waypointEdge0)

	return nil
}

type waypointEdgeWhere[Q psql.Filterable] struct {
	FromName  psql.WhereMod[Q, string]
	ToName    psql.WhereMod[Q, string]
	DistanceM psql.WhereMod[Q, float64]
}

func (waypointEdgeWhere[Q]) AliasedAs(alias string) waypointEdgeWhere[Q] {
	return buildWaypointEdgeWhere[Q](buildWaypointEdgeColumns(alias))
}

func buildWaypointEdgeWhere[Q psql.Filterable](cols waypointEdgeColumns) waypointEdgeWhere[Q] {
	return waypointEdgeWhere[Q]{
		FromName:  psql.Where[Q, string](cols.FromName),
		ToName:    psql.Where[Q, string](cols.ToName),
		DistanceM: psql.Where[Q, float64](cols.DistanceM),
	}
}

func (o *WaypointEdge) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "FromNameWaypoint":
		rel, ok := retrieved.(*Waypoint)
		if !ok {
			return fmt.Errorf("waypointEdge cannot load %T as %q", retrieved, name)
		}

		o.R.FromNameWaypoint = rel

		if rel != nil {
			rel.R.FromNameWaypointEdges = WaypointEdgeSlice{o}
		}
		return nil
	case "ToNameWaypoint":
		rel, ok := retrieved.(*Waypoint)
		if !ok {
			return fmt.Errorf("waypointEdge cannot load %T as %q", retrieved, name)
		}

		o.R.ToNameWaypoint = rel

		if rel != nil {
			rel.R.ToNameWaypointEdges = WaypointEdgeSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("waypointEdge has no relationship %q", name)
	}
}

type waypointEdgePreloader struct {
	FromNameWaypoint func(...psql.PreloadOption) psql.Preloader
	ToNameWaypoint   func(...psql.PreloadOption) psql.Preloader
}

func buildWaypointEdgePreloader() waypointEdgePreloader {
	return waypointEdgePreloader{
		FromNameWaypoint: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Waypoint, WaypointSlice](psql.PreloadRel{
				Name: "FromNameWaypoint",
				Sides: []psql.PreloadSide{
					{
						From:        WaypointEdges,
						To:          Waypoints,
						FromColumns: []string{"from_name"},
						ToColumns:   []string{"name"},
					},
				},
			}, Waypoints.Columns.Names(), opts...)
		},
		ToNameWaypoint: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Waypoint, WaypointSlice](psql.PreloadRel{
				Name: "ToNameWaypoint",
				Sides: []psql.PreloadSide{
					{
						From:        WaypointEdges,
						To:          Waypoints,
						FromColumns: []string{"to_name"},
						ToColumns:   []string{"name"},
					},
				},
			}, Waypoints.Columns.Names(), opts...)
		},
	}
}

type waypointEdgeThenLoader[Q orm.Loadable] struct {
	FromNameWaypoint func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ToNameWaypoint   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildWaypointEdgeThenLoader[Q orm.Loadable]() waypointEdgeThenLoader[Q] {
	type FromNameWaypointLoadInterface interface {
		LoadFromNameWaypoint(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ToNameWaypointLoadInterface interface {
		LoadToNameWaypoint(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return waypointEdgeThenLoader[Q]{
		FromNameWaypoint: thenLoadBuilder[Q](
			"FromNameWaypoint",
			func(ctx context.Context, exec bob.Executor, retrieved FromNameWaypointLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadFromNameWaypoint(ctx, exec, mods...)
			},
		),
		ToNameWaypoint: thenLoadBuilder[Q](
			"ToNameWaypoint",
			func(ctx context.Context, exec bob.Executor, retrieved ToNameWaypointLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadToNameWaypoint(ctx, exec, mods...)
			},
		),
	}
}

// LoadFromNameWaypoint loads the waypointEdge's FromNameWaypoint into the .R struct
func (o *WaypointEdge) LoadFromNameWaypoint(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.FromNameWaypoint = nil

	related, err := o.FromNameWaypoint(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.FromNameWaypointEdges = WaypointEdgeSlice{o}

	o.R.FromNameWaypoint = related
	return nil
}

// LoadFromNameWaypoint loads the waypointEdge's FromNameWaypoint into the .R struct
func (os WaypointEdgeSlice) LoadFromNameWaypoint(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	waypoints, err := os.FromNameWaypoint(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range waypoints {

			if !(o.FromName == rel.Name) {
				continue
			}

			rel.R.FromNameWaypointEdges = append(rel.R.FromNameWaypointEdges, o)

			o.R.FromNameWaypoint = rel
			break
		}
	}

	return nil
}

// LoadToNameWaypoint loads the waypointEdge's ToNameWaypoint into the .R struct
func (o *WaypointEdge) LoadToNameWaypoint(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ToNameWaypoint = nil

	related, err := o.ToNameWaypoint(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ToNameWaypointEdges = WaypointEdgeSlice{o}

	o.R.ToNameWaypoint = related
	return nil
}

// LoadToNameWaypoint loads the waypointEdge's ToNameWaypoint into the .R struct
func (os WaypointEdgeSlice) LoadToNameWaypoint(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	waypoints, err := os.ToNameWaypoint(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range waypoints {

			if !(o.ToName == rel.Name) {
				continue
			}

			rel.R.ToNameWaypointEdges = append(rel.R.ToNameWaypointEdges, o)

			o.R.ToNameWaypoint = rel
			break
		}
	}

	return nil
}

type waypointEdgeJoins[Q dialect.Joinable] struct {
	typ              string
	FromNameWaypoint modAs[Q, waypointColumns]
	ToNameWaypoint   modAs[Q, waypointColumns]
}

func (j waypointEdgeJoins[Q]) aliasedAs(alias string) waypointEdgeJoins[Q] {
	return buildWaypointEdgeJoins[Q](buildWaypointEdgeColumns(alias), j.typ)
}

func buildWaypointEdgeJoins[Q dialect.Joinable](cols waypointEdgeColumns, typ string) waypointEdgeJoins[Q] {
	return waypointEdgeJoins[Q]{
		typ: typ,
		FromNameWaypoint: modAs[Q, waypointColumns]{
			c: Waypoints.Columns,
			f: func(to waypointColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Waypoints.Name().As(to.Alias())).On(
						to.Name.EQ(cols.FromName),
					))
				}

				return mods
			},
		},
		ToNameWaypoint: modAs[Q, waypointColumns]{
			c: Waypoints.Columns,
			f: func(to waypointColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Waypoints.Name().As(to.Alias())).On(
						to.Name.EQ(cols.ToName),
					))
				}

				return mods
			},
		},
	}
}
