// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Waypoint is an object representing the database table.
type Waypoint struct {
	ID        int32            `db:"id,pk" `
	Name      string           `db:"name" `
	Latitude  float64          `db:"latitude" `
	Longitude float64          `db:"longitude" `
	Location  null.Val[string] `db:"location" `
	CreatedAt time.Time        `db:"created_at" `
	UpdatedAt time.Time        `db:"updated_at" `
	Grid      bool             `db:"grid" `

	R waypointR `db:"-" `
}

// WaypointSlice is an alias for a slice of pointers to Waypoint.
// This should almost always be used instead of []*Waypoint.
type WaypointSlice []*Waypoint

// Waypoints contains methods to work with the waypoints table
var Waypoints = psql.NewTablex[*Waypoint, WaypointSlice, *WaypointSetter]("", "waypoints", buildWaypointColumns("waypoints"))

// WaypointsQuery is a query on the waypoints table
type WaypointsQuery = *psql.ViewQuery[*Waypoint, WaypointSlice]

// waypointR is where relationships are stored.
type waypointR struct {
	FromNameWaypointEdges WaypointEdgeSlice // waypoint_edges.waypoint_edges_from_name_fkey
	ToNameWaypointEdges   WaypointEdgeSlice // waypoint_edges.waypoint_edges_to_name_fkey
}

func buildWaypointColumns(alias string) waypointColumns {
	return waypointColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "latitude", "longitude", "location", "created_at", "updated_at", "grid",
		).WithParent("waypoints"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		Name:       psql.Quote(alias, "name"),
		Latitude:   psql.Quote(alias, "latitude"),
		Longitude:  psql.Quote(alias, "longitude"),
		Location:   psql.Quote(alias, "location"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
		Grid:       psql.Quote(alias, "grid"),
	}
}

type waypointColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Name       psql.Expression
	Latitude   psql.Expression
	Longitude  psql.Expression
	Location   psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
	Grid       psql.Expression
}

func (c waypointColumns) Alias() string {
	return c.tableAlias
}

func (waypointColumns) AliasedAs(alias string) waypointColumns {
	return buildWaypointColumns(alias)
}

// WaypointSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type WaypointSetter struct {
	ID        omit.Val[int32]      `db:"id,pk" `
	Name      omit.Val[string]     `db:"name" `
	Latitude  omit.Val[float64]    `db:"latitude" `
	Longitude omit.Val[float64]    `db:"longitude" `
	Location  omitnull.Val[string] `db:"location" `
	CreatedAt omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt omit.Val[time.Time]  `db:"updated_at" `
	Grid      omit.Val[bool]       `db:"grid" `
}

func (s WaypointSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Latitude.IsValue() {
		vals = append(vals, "latitude")
	}
	if s.Longitude.IsValue() {
		vals = append(vals, "longitude")
	}
	if !s.Location.IsUnset() {
		vals = append(vals, "location")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if s.Grid.IsValue() {
		vals = append(vals, "grid")
	}
	return vals
}

func (s WaypointSetter) Overwrite(t *Waypoint) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Latitude.IsValue() {
		t.Latitude = s.Latitude.MustGet()
	}
	if s.Longitude.IsValue() {
		t.Longitude = s.Longitude.MustGet()
	}
	if !s.Location.IsUnset() {
		t.Location = s.Location.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if s.Grid.IsValue() {
		t.Grid = s.Grid.MustGet()
	}
}

func (s *WaypointSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Waypoints.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Latitude.IsValue() {
			vals[2] = psql.Arg(s.Latitude.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Longitude.IsValue() {
			vals[3] = psql.Arg(s.Longitude.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Location.IsUnset() {
			vals[4] = psql.Arg(s.Location.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[5] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[6] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.Grid.IsValue() {
			vals[7] = psql.Arg(s.Grid.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s WaypointSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s WaypointSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Latitude.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "latitude")...),
			psql.Arg(s.Latitude),
		}})
	}

	if s.Longitude.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "longitude")...),
			psql.Arg(s.Longitude),
		}})
	}

	if !s.Location.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "location")...),
			psql.Arg(s.Location),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.Grid.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "grid")...),
			psql.Arg(s.Grid),
		}})
	}

	return exprs
}

// FindWaypoint retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindWaypoint(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*Waypoint, error) {
	if len(cols) == 0 {
		return Waypoints.Query(
			sm.Where(Waypoints.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Waypoints.Query(
		sm.Where(Waypoints.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Waypoints.Columns.Only(cols...)),
	).One(ctx, exec)
}

// WaypointExists checks the presence of a single record by primary key
func WaypointExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return Waypoints.Query(
		sm.Where(Waypoints.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Waypoint is retrieved from the database
func (o *Waypoint) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Waypoints.AfterSelectHooks.RunHooks(ctx, exec, WaypointSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Waypoints.AfterInsertHooks.RunHooks(ctx, exec, WaypointSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Waypoints.AfterUpdateHooks.RunHooks(ctx, exec, WaypointSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Waypoints.AfterDeleteHooks.RunHooks(ctx, exec, WaypointSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Waypoint
func (o *Waypoint) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Waypoint) pkEQ() dialect.Expression {
	return psql.Quote("waypoints", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Waypoint
func (o *Waypoint) Update(ctx context.Context, exec bob.Executor, s *WaypointSetter) error {
	v, err := Waypoints.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Waypoint record with an executor
func (o *Waypoint) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Waypoints.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Waypoint using the executor
func (o *Waypoint) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Waypoints.Query(
		sm.Where(Waypoints.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after WaypointSlice is retrieved from the database
func (o WaypointSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Waypoints.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Waypoints.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Waypoints.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Waypoints.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o WaypointSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("waypoints", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o WaypointSlice) copyMatchingRows(from ...*Waypoint) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o WaypointSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Waypoints.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Waypoint:
				o.copyMatchingRows(retrieved)
			case []*Waypoint:
				o.copyMatchingRows(retrieved...)
			case WaypointSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Waypoint or a slice of Waypoint
				// then run the AfterUpdateHooks on the slice
				_, err = Waypoints.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o WaypointSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Waypoints.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Waypoint:
				o.copyMatchingRows(retrieved)
			case []*Waypoint:
				o.copyMatchingRows(retrieved...)
			case WaypointSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Waypoint or a slice of Waypoint
				// then run the AfterDeleteHooks on the slice
				_, err = Waypoints.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o WaypointSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals WaypointSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Waypoints.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o WaypointSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Waypoints.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o WaypointSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Waypoints.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// FromNameWaypointEdges starts a query for related objects on waypoint_edges
func (o *Waypoint) FromNameWaypointEdges(mods ...bob.Mod[*dialect.SelectQuery]) WaypointEdgesQuery {
	return WaypointEdges.Query(append(mods,
		sm.Where(WaypointEdges.Columns.FromName.EQ(psql.Arg(o.Name))),
	)...)
}

func (os WaypointSlice) FromNameWaypointEdges(mods ...bob.Mod[*dialect.SelectQuery]) WaypointEdgesQuery {
	pkName := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkName = append(pkName, o.Name)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkName), "character varying[]")),
	))

	return WaypointEdges.Query(append(mods,
		sm.Where(psql.Group(WaypointEdges.Columns.FromName).OP("IN", PKArgExpr)),
	)...)
}

// ToNameWaypointEdges starts a query for related objects on waypoint_edges
func (o *Waypoint) ToNameWaypointEdges(mods ...bob.Mod[*dialect.SelectQuery]) WaypointEdgesQuery {
	return WaypointEdges.Query(append(mods,
		sm.Where(WaypointEdges.Columns.ToName.EQ(psql.Arg(o.Name))),
	)...)
}

func (os WaypointSlice) ToNameWaypointEdges(mods ...bob.Mod[*dialect.SelectQuery]) WaypointEdgesQuery {
	pkName := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkName = append(pkName, o.Name)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkName), "character varying[]")),
	))

	return WaypointEdges.Query(append(mods,
		sm.Where(psql.Group(WaypointEdges.Columns.ToName).OP("IN", PKArgExpr)),
	)...)
}

func insertWaypointFromNameWaypointEdges0(ctx context.Context, exec bob.Executor, waypointEdges1 []*WaypointEdgeSetter, waypoint0 *Waypoint) (WaypointEdgeSlice, error) {
	for i := range waypointEdges1 {
		waypointEdges1[i].FromName = omit.From(waypoint0.Name)
	}

	ret, err := WaypointEdges.Insert(bob.ToMods(waypointEdges1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertWaypointFromNameWaypointEdges0: %w", err)
	}

	return ret, nil
}

func attachWaypointFromNameWaypointEdges0(ctx context.Context, exec bob.Executor, count int, waypointEdges1 WaypointEdgeSlice, waypoint0 *Waypoint) (WaypointEdgeSlice, error) {
	setter := &WaypointEdgeSetter{
		FromName: omit.From(waypoint0.Name),
	}

	err := waypointEdges1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachWaypointFromNameWaypointEdges0: %w", err)
	}

	return waypointEdges1, nil
}

func (waypoint0 *Waypoint) InsertFromNameWaypointEdges(ctx context.Context, exec bob.Executor, related ...*WaypointEdgeSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	waypointEdges1, err := insertWaypointFromNameWaypointEdges0(ctx, exec, related, waypoint0)
	if err != nil {
		return err
	}

	waypoint0.R.FromNameWaypointEdges = append(waypoint0.R.FromNameWaypointEdges, waypointEdges1...)

	for _, rel := range waypointEdges1 {
		rel.R.FromNameWaypoint = waypoint0
	}
	return nil
}

func (waypoint0 *Waypoint) AttachFromNameWaypointEdges(ctx context.Context, exec bob.Executor, related ...*WaypointEdge) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	waypointEdges1 := WaypointEdgeSlice(related)

	_, err = attachWaypointFromNameWaypointEdges0(ctx, exec, len(related), waypointEdges1, waypoint0)
	if err != nil {
		return err
	}

	waypoint0.R.FromNameWaypointEdges = append(waypoint0.R.FromNameWaypointEdges, waypointEdges1...)

	for _, rel := range related {
		rel.R.FromNameWaypoint = waypoint0
	}

	return nil
}

func insertWaypointToNameWaypointEdges0(ctx context.Context, exec bob.Executor, waypointEdges1 []*WaypointEdgeSetter, waypoint0 *Waypoint) (WaypointEdgeSlice, error) {
	for i := range waypointEdges1 {
		waypointEdges1[i].ToName = omit.From(waypoint0.Name)
	}

	ret, err := WaypointEdges.Insert(bob.ToMods(waypointEdges1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertWaypointToNameWaypointEdges0: %w", err)
	}

	return ret, nil
}

func attachWaypointToNameWaypointEdges0(ctx context.Context, exec bob.Executor, count int, waypointEdges1 WaypointEdgeSlice, waypoint0 *Waypoint) (WaypointEdgeSlice, error) {
	setter := &WaypointEdgeSetter{
		ToName: omit.From(waypoint0.Name),
	}

	err := waypointEdges1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachWaypointToNameWaypointEdges0: %w", err)
	}

	return waypointEdges1, nil
}

func (waypoint0 *Waypoint) InsertToNameWaypointEdges(ctx context.Context, exec bob.Executor, related ...*WaypointEdgeSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	waypointEdges1, err := insertWaypointToNameWaypointEdges0(ctx, exec, related, waypoint0)
	if err != nil {
		return err
	}

	waypoint0.R.ToNameWaypointEdges = append(waypoint0.R.ToNameWaypointEdges, waypointEdges1...)

	for _, rel := range waypointEdges1 {
		rel.R.ToNameWaypoint = waypoint0
	}
	return nil
}

func (waypoint0 *Waypoint) AttachToNameWaypointEdges(ctx context.Context, exec bob.Executor, related ...*WaypointEdge) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	waypointEdges1 := WaypointEdgeSlice(related)

	_, err = attachWaypointToNameWaypointEdges0(ctx, exec, len(related), waypointEdges1, waypoint0)
	if err != nil {
		return err
	}

	waypoint0.R.ToNameWaypointEdges = append(waypoint0.R.ToNameWaypointEdges, waypointEdges1...)

	for _, rel := range related {
		rel.R.ToNameWaypoint = waypoint0
	}

	return nil
}

type waypointWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int32]
	Name      psql.WhereMod[Q, string]
	Latitude  psql.WhereMod[Q, float64]
	Longitude psql.WhereMod[Q, float64]
	Location  psql.WhereNullMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
	Grid      psql.WhereMod[Q, bool]
}

func (waypointWhere[Q]) AliasedAs(alias string) waypointWhere[Q] {
	return buildWaypointWhere[Q](buildWaypointColumns(alias))
}

func buildWaypointWhere[Q psql.Filterable](cols waypointColumns) waypointWhere[Q] {
	return waypointWhere[Q]{
		ID:        psql.Where[Q, int32](cols.ID),
		Name:      psql.Where[Q, string](cols.Name),
		Latitude:  psql.Where[Q, float64](cols.Latitude),
		Longitude: psql.Where[Q, float64](cols.Longitude),
		Location:  psql.WhereNull[Q, string](cols.Location),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
		Grid:      psql.Where[Q, bool](cols.Grid),
	}
}

func (o *Waypoint) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "FromNameWaypointEdges":
		rels, ok := retrieved.(WaypointEdgeSlice)
		if !ok {
			return fmt.Errorf("waypoint cannot load %T as %q", retrieved, name)
		}

		o.R.FromNameWaypointEdges = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.FromNameWaypoint = o
			}
		}
		return nil
	case "ToNameWaypointEdges":
		rels, ok := retrieved.(WaypointEdgeSlice)
		if !ok {
			return fmt.Errorf("waypoint cannot load %T as %q", retrieved, name)
		}

		o.R.ToNameWaypointEdges = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.ToNameWaypoint = o
			}
		}
		return nil
	default:
		return fmt.Errorf("waypoint has no relationship %q", name)
	}
}

type waypointPreloader struct{}

func buildWaypointPreloader() waypointPreloader {
	return waypointPreloader{}
}

type waypointThenLoader[Q orm.Loadable] struct {
	FromNameWaypointEdges func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ToNameWaypointEdges   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildWaypointThenLoader[Q orm.Loadable]() waypointThenLoader[Q] {
	type FromNameWaypointEdgesLoadInterface interface {
		LoadFromNameWaypointEdges(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ToNameWaypointEdgesLoadInterface interface {
		LoadToNameWaypointEdges(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return waypointThenLoader[Q]{
		FromNameWaypointEdges: thenLoadBuilder[Q](
			"FromNameWaypointEdges",
			func(ctx context.Context, exec bob.Executor, retrieved FromNameWaypointEdgesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadFromNameWaypointEdges(ctx, exec, mods...)
			},
		),
		ToNameWaypointEdges: thenLoadBuilder[Q](
			"ToNameWaypointEdges",
			func(ctx context.Context, exec bob.Executor, retrieved ToNameWaypointEdgesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadToNameWaypointEdges(ctx, exec, mods...)
			},
		),
	}
}

// LoadFromNameWaypointEdges loads the waypoint's FromNameWaypointEdges into the .R struct
func (o *Waypoint) LoadFromNameWaypointEdges(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.FromNameWaypointEdges = nil

	related, err := o.FromNameWaypointEdges(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.FromNameWaypoint = o
	}

	o.R.FromNameWaypointEdges = related
	return nil
}

// LoadFromNameWaypointEdges loads the waypoint's FromNameWaypointEdges into the .R struct
func (os WaypointSlice) LoadFromNameWaypointEdges(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	waypointEdges, err := os.FromNameWaypointEdges(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.FromNameWaypointEdges = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range waypointEdges {

			if !(o.Name == rel.FromName) {
				continue
			}

			rel.R.FromNameWaypoint = o

			o.R.FromNameWaypointEdges = append(o.R.FromNameWaypointEdges, rel)
		}
	}

	return nil
}

// LoadToNameWaypointEdges loads the waypoint's ToNameWaypointEdges into the .R struct
func (o *Waypoint) LoadToNameWaypointEdges(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ToNameWaypointEdges = nil

	related, err := o.ToNameWaypointEdges(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.ToNameWaypoint = o
	}

	o.R.ToNameWaypointEdges = related
	return nil
}

// LoadToNameWaypointEdges loads the waypoint's ToNameWaypointEdges into the .R struct
func (os WaypointSlice) LoadToNameWaypointEdges(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	waypointEdges, err := os.ToNameWaypointEdges(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ToNameWaypointEdges = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range waypointEdges {

			if !(o.Name == rel.ToName) {
				continue
			}

			rel.R.ToNameWaypoint = o

			o.R.ToNameWaypointEdges = append(o.R.ToNameWaypointEdges, rel)
		}
	}

	return nil
}

type waypointJoins[Q dialect.Joinable] struct {
	typ                   string
	FromNameWaypointEdges modAs[Q, waypointEdgeColumns]
	ToNameWaypointEdges   modAs[Q, waypointEdgeColumns]
}

func (j waypointJoins[Q]) aliasedAs(alias string) waypointJoins[Q] {
	return buildWaypointJoins[Q](buildWaypointColumns(alias), j.typ)
}

func buildWaypointJoins[Q dialect.Joinable](cols waypointColumns, typ string) waypointJoins[Q] {
	return waypointJoins[Q]{
		typ: typ,
		FromNameWaypointEdges: modAs[Q, waypointEdgeColumns]{
			c: WaypointEdges.Columns,
			f: func(to waypointEdgeColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, WaypointEdges.Name().As(to.Alias())).On(
						to.FromName.EQ(cols.Name),
					))
				}

				return mods
			},
		},
		ToNameWaypointEdges: modAs[Q, waypointEdgeColumns]{
			c: WaypointEdges.Columns,
			f: func(to waypointEdgeColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, WaypointEdges.Name().As(to.Alias())).On(
						to.ToName.EQ(cols.Name),
					))
				}

				return mods
			},
		},
	}
}
